import { mk, type Raw } from './mk';

// Old Testament, part 2. Verses are KJV.
const RAW: Raw[] = [
  ['miriam-song', 'Miriam’s Song by the Sea', 'Exodus 15:1–21', 'sea', 'harp',
    ['God’s people stood safely on the far shore of the Red Sea. Behind them the water had closed; the enemy was gone.', 'Miriam, Moses’ sister, picked up her tambourine. All the women followed her, dancing and singing.', '“Sing to the Lord, for He has triumphed gloriously!” The whole nation praised God for the miracle they had seen.'],
    'The LORD is my strength and song, and he is become my salvation.', 'Exodus 15:2',
    'When God does great things, praise Him loudly and joyfully.',
    'Thanksgiving is not just good manners; it keeps your heart full of faith. When you remember what God has done, you are ready for what He will do. Revelation 15:3 says believers in heaven sing “the song of Moses and the Lamb”: praise for complete victory.',
    'The Lord is my strength and my song. I celebrate His victory in my life.',
    'Lord, You have done great things for me, and I praise You! Amen.', 'Make up a short song of thanks to God and sing it.',
    [['What did Miriam play?', 'A harp', 'A tambourine', 'A trumpet', 1], ['Why were they singing?', 'God saved them at the sea', 'It was a birthday', 'They found gold', 0], ['Who was Miriam’s brother?', 'Moses', 'Joshua', 'Caleb', 0]],
    'MIRIAM:Moses’ sister|SING:Do it to the Lord|DANCE:The women did it|SONG:The Lord is my strength and ___|PRAISE:Give it to God'],
  ['hands-raised', 'Moses’ Hands Held High', 'Exodus 17:8–16', 'mountain', 'staff',
    ['The Amalekites attacked God’s people. Joshua led the fighters while Moses stood on a hill with the staff of God raised high.', 'When Moses’ hands were up, Israel won. When he got tired and his hands dropped, the enemy started winning!', 'So Aaron and Hur sat Moses on a stone and held up his hands, one on each side, until sunset. Israel won, and Moses built an altar called “The Lord is my banner.”'],
    'Bear ye one another’s burdens.', 'Galatians 6:2',
    'Nobody is meant to fight alone. We win together.',
    'Raised hands are a picture of prayer and dependence on God. Aaron and Hur show the power of standing with others in prayer. Victory came through intercession. When you pray for your pastor, friends and family, you are holding up their hands.',
    'The Lord is my banner. I pray for others and they are strengthened.',
    'Lord, help me to support others and pray for them. Amen.', 'Pray today for your pastor and one friend by name.',
    [['Who held up Moses’ hands?', 'Aaron and Hur', 'Joshua and Caleb', 'David and Jonathan', 0], ['What happened when his hands dropped?', 'Israel won', 'The enemy started winning', 'It rained', 1], ['What did Moses name the altar?', 'The Lord is my banner', 'The Lord is near', 'The Lord is king', 0]],
    'AARON:Held one hand|HUR:Held the other hand|BANNER:The Lord is my ___|HANDS:Lifted high|ALTAR:Moses built one'],
  ['gideon-fleece', 'Gideon’s Fleece', 'Judges 6:36–40', 'field', 'dove',
    ['Gideon wanted to be sure God would help him. He put a wool fleece on the ground and prayed, “Make it wet with dew and the ground dry.”', 'In the morning the fleece was so wet he squeezed out a bowl of water, but the ground was dry!', 'Gideon asked once more, the other way round. The next morning the fleece was dry and the ground was wet. God was patient with Gideon’s questions.'],
    'Like as a father pitieth his children, so the LORD pitieth them that fear him.', 'Psalm 103:13',
    'God is patient with us when we are learning to trust Him.',
    'God was kind to Gideon in his weakness. But in the New Covenant we have something better than fleeces: the written Word and the Holy Spirit inside. Learn to trust what God has said. His Word is the surest sign you will ever get (2 Peter 1:19).',
    'God’s Word is my sure guide. I do not need to doubt what He has said.',
    'Father, thank You for being patient with me. Help me trust Your Word. Amen.', 'Find one promise in the Bible and decide to believe it all day.',
    [['What did Gideon put on the ground?', 'A fleece', 'A stone', 'A sword', 0], ['What was it the first morning?', 'Wet', 'Dry', 'Gone', 0], ['What does God give us now?', 'His Word and Spirit', 'Nothing', 'Only fleeces', 0]],
    'FLEECE:Wool on the ground|DEW:Morning water|GIDEON:He asked for a sign|PATIENT:God was ___|WOOL:A fleece is made of it'],
  ['hezekiah', 'Hezekiah Spreads the Letter', '2 Kings 19', 'temple', 'scroll',
    ['A mighty king of Assyria sent King Hezekiah a scary letter: “No god has saved any nation from me. Your God cannot save you!”', 'Hezekiah did not panic. He took the letter into the temple, spread it out before the Lord and prayed, “Lord, You alone are God. Save us!”', 'God answered through Isaiah. That night the angel of the Lord struck the enemy camp, and the king of Assyria went home in defeat.'],
    'O LORD our God, I beseech thee, save thou us out of his hand.', '2 Kings 19:19',
    'When something scares you, show it to God first.',
    'Hezekiah answered threats by laying them before God. Philippians 4:6 says in everything, by prayer with thanksgiving, let your requests be made known. Prayer shifts the burden from your shoulders to God’s. Peace that passes understanding guards your heart.',
    'I do not worry. I bring everything to God, and His peace guards my heart.',
    'Lord, I bring You my worries, and I trust You. Amen.', 'Write down one worry, pray about it, then tear up the paper.',
    [['What did the enemy send?', 'A letter', 'A gift', 'A song', 0], ['Where did Hezekiah take it?', 'Into the temple', 'To his bed', 'To the river', 0], ['Who defeated the enemy?', 'The angel of the Lord', 'Hezekiah’s army', 'A storm', 0]],
    'LETTER:Full of threats|HEZEKIAH:The praying king|ISAIAH:The prophet|ANGEL:Defended the city|PRAYER:Hezekiah’s answer'],
  ['jehoshaphat', 'The Singing Army', '2 Chronicles 20', 'desert', 'harp',
    ['Three armies came against King Jehoshaphat. He was afraid, but he called everyone to pray and fast. “We do not know what to do, but our eyes are on You.”', 'God said, “The battle is not yours, but God’s.” So Jehoshaphat put singers at the front of the army, praising the beauty of holiness.', 'When they began to sing, God set ambushes, and the enemy armies turned on each other. God’s people just collected the spoil for three days!'],
    'The battle is not yours, but God’s.', '2 Chronicles 20:15',
    'Praise is a powerful weapon.',
    'They praised before they saw victory. Praise is faith singing. Psalm 22:3 says God inhabits the praises of His people. When you worship in a hard situation, you invite God into it and declare that He has already won.',
    'The battle is the Lord’s. I praise Him and I see His victory.',
    'Lord, my eyes are on You. I praise You for victory. Amen.', 'Next time you feel worried today, sing a praise song instead.',
    [['Who went in front of the army?', 'Singers', 'Horses', 'Archers', 0], ['Whose battle was it?', 'The king’s', 'God’s', 'The soldiers’', 1], ['How long did they collect spoil?', 'One day', 'Three days', 'Forty days', 1]],
    'SINGERS:At the front|PRAISE:A powerful weapon|BATTLE:It is God’s|EYES:Our ___ are on You|SPOIL:Collected for three days'],
  ['nehemiah', 'Nehemiah Rebuilds the Wall', 'Nehemiah 1–6', 'city', 'wall',
    ['Nehemiah heard that Jerusalem’s walls were broken down. He wept, fasted and prayed. Then God moved the king of Persia to send him to rebuild.', 'Everyone worked on a section. Enemies mocked them: “Even a fox would break this wall!” Nehemiah prayed and kept building. Builders worked with a tool in one hand and a sword in the other.', 'In just fifty-two days the wall was finished! Even the enemies knew it was God’s work.'],
    'The God of heaven, he will prosper us; therefore we his servants will arise and build.', 'Nehemiah 2:20',
    'Keep going with God’s work, even when people laugh.',
    'Nehemiah built and guarded at the same time. A believer builds up by the Word and guards with the sword of the Spirit, which is the Word too (Ephesians 6:17). Build your life on prayer and Scripture, and stand against discouragement.',
    'I build my life on the Word. I finish what God gives me to do.',
    'Lord, help me finish what I start for You. Amen.', 'Finish one task you started and left undone.',
    [['What did Nehemiah rebuild?', 'Jerusalem’s wall', 'A ship', 'A palace', 0], ['What did builders hold?', 'A tool and a sword', 'A lamp and a jar', 'Two swords', 0], ['How many days did it take?', 'Seven', 'Fifty-two', 'One hundred', 1]],
    'NEHEMIAH:He rebuilt the wall|WALL:Around Jerusalem|BUILD:Arise and ___|SWORD:Held in one hand|FINISH:Done in 52 days'],
  ['daniel-food', 'Daniel’s Brave Choice', 'Daniel 1', 'palace', 'crown',
    ['Daniel and his friends were taken to Babylon to be trained for the king. They were given the king’s rich food, which had been offered to idols.', 'Daniel purposed in his heart not to defile himself. He politely asked, “Test us for ten days with vegetables and water.”', 'After ten days they looked healthier than everyone else! God gave them knowledge and wisdom, and they were ten times better than all the king’s wise men.'],
    'But Daniel purposed in his heart that he would not defile himself.', 'Daniel 1:8',
    'Decide ahead of time what is right, and God will honour you.',
    'Daniel made his decision in his heart before the pressure came. Consecration means setting yourself apart for God. You live in the world but you are not of it (John 17:16). God gives excellence to those who honour Him; Daniel had “an excellent spirit” (Daniel 6:3).',
    'I have an excellent spirit. I am set apart for God and He gives me wisdom.',
    'Lord, help me make right choices even when others don’t. Amen.', 'Decide one good habit and keep it for ten days.',
    [['Where was Daniel taken?', 'Egypt', 'Babylon', 'Rome', 1], ['What did Daniel ask to eat?', 'Vegetables and water', 'Meat and wine', 'Cake', 0], ['How much wiser were they?', 'Twice', 'Ten times', 'A little', 1]],
    'DANIEL:He purposed in his heart|BABYLON:Where he was taken|PURPOSE:Decide firmly|WISDOM:God gave it|EXCELLENT:Daniel had an ___ spirit'],
  ['handwriting', 'Writing on the Wall', 'Daniel 5', 'palace', 'lamp',
    ['King Belshazzar threw a huge party. He drank from golden cups stolen from God’s temple and praised idols.', 'Suddenly fingers of a hand appeared and wrote on the palace wall! The king’s knees knocked together. No wise man could read it.', 'Daniel was called. He read it: God has numbered your kingdom and finished it. That very night the kingdom fell, just as God said.'],
    'Be not deceived; God is not mocked.', 'Galatians 6:7',
    'God sees everything, and His Word always comes to pass.',
    'Daniel was the only one who could read the writing, because the Spirit of God was in him (Daniel 5:11). The world needs believers who carry God’s Spirit and can explain what God is saying. You have the Spirit of God in you too, and with Him comes understanding.',
    'The Spirit of God in me gives me light, understanding and wisdom.',
    'Holy Spirit, give me understanding and help me honour You. Amen.', 'Treat something that belongs to God, like your Bible, with special care today.',
    [['What did the king drink from?', 'Temple cups', 'A river', 'A bottle', 0], ['What appeared on the wall?', 'A hand writing', 'A painting', 'A door', 0], ['Who read the writing?', 'Daniel', 'The king', 'A soldier', 0]],
    'WALL:Writing appeared on it|HAND:Its fingers wrote|DANIEL:He read the message|KING:Belshazzar|CUPS:Taken from the temple'],
  ['dry-bones', 'The Valley of Dry Bones', 'Ezekiel 37:1–14', 'desert', 'dove',
    ['God took Ezekiel to a valley full of very dry bones. “Can these bones live?” God asked. Ezekiel said, “Lord, You know.”', 'God said, “Prophesy to the bones!” As Ezekiel spoke God’s Word, there was a rattling; bones joined together and were covered with muscle and skin!', 'Then God said, “Prophesy to the breath.” Breath came into them and they stood up, a huge army. God can bring life to anything!'],
    'O ye dry bones, hear the word of the LORD.', 'Ezekiel 37:4',
    'When God’s Word is spoken, dead things come alive.',
    'Nothing happened until Ezekiel spoke. God works through the Word spoken in faith. The breath is a picture of the Holy Spirit, the one who gives life (John 6:63). Speak God’s Word over situations that look dead, and watch the Spirit bring life.',
    'I speak God’s Word, and the Spirit of life brings dead things alive.',
    'Holy Spirit, breathe on my life, my family and my school. Amen.', 'Speak a Bible verse over something that looks hopeless.',
    [['What filled the valley?', 'Dry bones', 'Flowers', 'Water', 0], ['What did God tell Ezekiel to do?', 'Run away', 'Prophesy', 'Dig', 1], ['What came into the bodies?', 'Breath', 'Light', 'Water', 0]],
    'BONES:Very dry ones|EZEKIEL:The prophet|BREATH:Brought them to life|ARMY:They stood up as one|PROPHESY:Speak God’s Word'],
  ['isaiah-vision', 'Here Am I, Send Me', 'Isaiah 6', 'temple', 'lamp',
    ['Isaiah saw the Lord on a throne, high and lifted up. Angels called seraphim cried, “Holy, holy, holy is the Lord of hosts!” and the temple shook.', 'Isaiah said, “Woe is me! I have unclean lips.” An angel touched his lips with a hot coal from the altar: “Your sin is taken away.”', 'Then God asked, “Whom shall I send?” Isaiah answered right away, “Here am I; send me!”'],
    'Here am I; send me.', 'Isaiah 6:8',
    'When you see how great God is, you want to serve Him.',
    'Isaiah needed cleansing before sending. You have been cleansed by the blood of Jesus once and for all (Hebrews 10:10). You are not waiting to be good enough; you are already made worthy in Christ. Now God asks, “Who will go?” Your yes matters.',
    'I am cleansed by the blood of Jesus. Here am I, Lord, send me.',
    'Lord, here I am. Use me. Amen.', 'Tell one person about Jesus this week.',
    [['What did the angels cry?', 'Holy, holy, holy', 'Hello', 'Hallelujah', 0], ['What touched Isaiah’s lips?', 'A hot coal', 'Water', 'Oil', 0], ['What did Isaiah say?', 'Send someone else', 'Here am I, send me', 'Not now', 1]],
    'ISAIAH:He saw the Lord|HOLY:Said three times|COAL:Touched his lips|SEND:Here am I, ___ me|THRONE:High and lifted up'],
  ['jeremiah-call', 'Too Young? Not with God', 'Jeremiah 1:4–10', 'field', 'scroll',
    ['God spoke to young Jeremiah: “Before I formed you in the womb, I knew you. I chose you to be a prophet to the nations.”', 'Jeremiah said, “Ah, Lord God! I cannot speak, I am only a child.”', 'God said, “Do not say you are only a child. Go where I send you and speak what I command. Do not be afraid.” Then God touched his mouth: “I have put My words in your mouth.”'],
    'Before I formed thee in the belly I knew thee.', 'Jeremiah 1:5',
    'God knew you before you were born, and He has plans for you now, not only later.',
    'God told Jeremiah not to say “I am only a child.” Words of limitation must be replaced with words of faith. 1 Timothy 4:12 says let no one despise your youth. You are not the church of tomorrow; you are part of the church today.',
    'God knew me before I was born. His words are in my mouth, and I am not afraid.',
    'Lord, put Your words in my mouth and use me now. Amen.', 'Stop saying “I can’t” today. Say “I can through Christ” instead.',
    [['When did God know Jeremiah?', 'Before he was born', 'When he was old', 'At school', 0], ['What excuse did Jeremiah give?', 'I am a child', 'I am busy', 'I am sick', 0], ['What did God put in his mouth?', 'Honey', 'His words', 'A coal', 1]],
    'JEREMIAH:The young prophet|WORDS:God put His ___ in his mouth|CHILD:Do not say I am only a ___|CHOSEN:Picked by God|NATIONS:He spoke to them'],
  ['potter', 'The Potter and the Clay', 'Jeremiah 18:1–6', 'city', 'jar',
    ['God sent Jeremiah to watch a potter at his wheel. The potter was shaping a jar from soft, wet clay.', 'The jar did not turn out right. But the potter did not throw the clay away. He squashed it and made it again into a new jar.', 'God said, “As the clay is in the potter’s hand, so are you in Mine.” God never gives up on us; He keeps shaping us into something beautiful.'],
    'We are the clay, and thou our potter; and we all are the work of thy hand.', 'Isaiah 64:8',
    'Stay soft in God’s hands and let Him shape you.',
    'God shapes us through His Word and Holy Spirit. Romans 8:29 says we are being conformed to the image of His Son. Soft clay is a teachable heart. Mistakes are not the end; in God’s hands they become part of the story of His grace.',
    'I am God’s workmanship. I am soft in His hands and He is making me like Jesus.',
    'Father, shape me into what You want me to be. Amen.', 'Make something from clay, dough or paper and thank God for making you.',
    [['Who did Jeremiah watch?', 'A potter', 'A fisherman', 'A farmer', 0], ['What did the potter do with the spoiled jar?', 'Threw it away', 'Made it again', 'Sold it', 1], ['Who is our Potter?', 'God', 'Our teacher', 'Ourselves', 0]],
    'POTTER:He shapes clay|CLAY:We are the ___|WHEEL:The potter’s tool|SHAPE:God does it to us|JAR:What he made'],
  ['job', 'Job Never Gave Up', 'Job 1–2; 42', 'field', 'sun',
    ['Job was a good man who loved God and was very rich. Then the devil attacked him: he lost his animals, his house and his children, and he became very sick.', 'Job’s friends gave him wrong answers and blamed him. Job had questions, but he did not curse God. He said, “I know that my Redeemer lives!”', 'At last God spoke to Job. Job prayed for his friends, and God turned everything around, giving him twice as much as before!'],
    'For I know that my redeemer liveth.', 'Job 19:25',
    'The devil steals, but God restores.',
    'James 5:11 says the end of Job’s story shows the Lord is very pitiful and of tender mercy. Jesus made it clear: the thief comes to steal, kill and destroy, but He came to give life abundantly (John 10:10). Never blame God for the devil’s work. The turnaround came when Job prayed for his friends.',
    'My Redeemer lives. God restores me, and I have abundant life.',
    'Lord, even when things are hard, I trust You. Amen.', 'Pray for a friend who is going through something hard.',
    [['Who attacked Job?', 'The devil', 'God', 'A lion', 0], ['What did Job say?', 'My Redeemer lives', 'I give up', 'I am angry', 0], ['How much did Job get back?', 'Half', 'The same', 'Twice as much', 2]],
    'JOB:He never gave up|REDEEMER:Job said mine lives|DOUBLE:Twice as much|RESTORE:God does it|PATIENCE:Job is known for it'],
  ['caleb-mountain', 'Give Me This Mountain', 'Joshua 14:6–14', 'mountain', 'staff',
    ['Forty-five years after he spied out the land, Caleb was eighty-five years old. Now the land was being shared out.', 'Caleb said to Joshua, “I am as strong today as I was back then. Give me this mountain, where the giants live! The Lord will be with me.”', 'Joshua blessed him and gave him Hebron. Caleb drove out the giants and took his mountain. He wholly followed the Lord all his life.'],
    'He wholly followed the LORD God of Israel.', 'Joshua 14:14',
    'Faith that starts strong can stay strong all your life.',
    'Caleb kept his faith fresh for forty-five years while waiting. He did not let others’ unbelief steal his promise. Isaiah 40:31 says those who wait on the Lord renew their strength. Faith does not retire; it keeps believing and keeps possessing.',
    'I wholly follow the Lord. My faith stays strong and I possess my mountain.',
    'Lord, keep my faith strong all my life. Amen.', 'Ask an older Christian how God has been faithful to them.',
    [['How old was Caleb?', 'Forty', 'Eighty-five', 'Twelve', 1], ['What did Caleb ask for?', 'Gold', 'A mountain', 'A rest', 1], ['Who lived on the mountain?', 'Giants', 'Shepherds', 'Lions', 0]],
    'CALEB:Give me this mountain|HEBRON:The place he received|WHOLLY:He ___ followed the Lord|STRONG:As ___ as before|MOUNTAIN:Caleb’s request'],
  ['young-king-joash', 'Joash, Hidden in the Temple', '2 Kings 11–12', 'temple', 'crown',
    ['A wicked queen tried to destroy all the royal family. But baby Joash was rescued by his aunt and hidden in God’s temple for six years.', 'When Joash was seven, the priest Jehoiada brought him out, put the crown on his head and everyone shouted, “God save the king!”', 'Joash repaired God’s temple. As long as he listened to Jehoiada’s teaching, he did what was right in God’s eyes.'],
    'Train up a child in the way he should go: and when he is old, he will not depart from it.', 'Proverbs 22:6',
    'Growing up close to God’s house and God’s Word keeps you safe.',
    'Joash grew up hidden in God’s presence. The secret place of the Most High is where you are protected (Psalm 91:1). Also notice: Joash did well while he listened to a godly teacher. Honour the spiritual leaders God places in your life.',
    'I dwell in the secret place of the Most High. I grow up in God’s presence.',
    'Thank You, Lord, for my church and for people who teach me Your Word. Amen.', 'Thank a Sunday school teacher or leader this week.',
    [['How old was Joash when he became king?', 'Seven', 'Twelve', 'Twenty', 0], ['Where was he hidden?', 'In the temple', 'In a cave', 'In Egypt', 0], ['What did Joash repair?', 'The temple', 'A ship', 'The wall', 0]],
    'JOASH:Boy king at seven|HIDDEN:Kept in the temple|CROWN:Placed on his head|TEMPLE:God’s house|PRIEST:Jehoiada was one'],
  ['naaman-maid', 'The Little Servant Girl', '2 Kings 5:1–4', 'palace', 'jar',
    ['A young Israelite girl was taken far from home to Syria. She became a servant to the wife of Naaman, an army captain who had leprosy.', 'She could have been bitter, but instead she cared. She said, “If only my master would go to the prophet in Samaria! He would heal him.”', 'Naaman listened, went to Elisha and was healed. One little girl’s faith and kind words changed a great man’s life.'],
    'Let no man despise thy youth.', '1 Timothy 4:12',
    'Your words about God can change someone’s life, no matter how young you are.',
    'We do not even know her name, but heaven does. She carried faith into a foreign land. You are a light wherever you are placed (Matthew 5:14). Being a witness is simply telling people where help is found: in Jesus.',
    'I am the light of the world. My words point people to Jesus.',
    'Lord, help me tell others where help is found. Amen.', 'Tell a friend something good that God has done.',
    [['Who did the girl serve?', 'Naaman’s wife', 'The king', 'Elisha', 0], ['What sickness did Naaman have?', 'Leprosy', 'Fever', 'Blindness', 0], ['Who did she say could heal him?', 'The prophet', 'A doctor', 'The king', 0]],
    'MAID:A young servant girl|NAAMAN:Army captain|SYRIA:Where she lived|PROPHET:Elisha|WITNESS:Someone who tells'],
  ['elisha-cloak', 'Elijah’s Cloak Falls', '2 Kings 2', 'river', 'dove',
    ['Elisha followed Elijah everywhere. Elijah said, “What shall I do for you before I am taken?” Elisha said, “Let a double portion of your spirit be on me.”', 'As they walked, a chariot of fire with horses of fire appeared, and Elijah went up to heaven in a whirlwind! His cloak fell to the ground.', 'Elisha picked it up, struck the Jordan River and cried, “Where is the Lord God of Elijah?” The water parted! The same power was now on Elisha.'],
    'Let a double portion of thy spirit be upon me.', '2 Kings 2:9',
    'Stay close to God and to godly people. Hunger for more of God.',
    'Elisha received what he was hungry for. Jesus said those who hunger and thirst for righteousness shall be filled (Matthew 5:6). In the New Testament, every believer can be filled with the Holy Spirit. Ask, and your Father gives the Holy Spirit (Luke 11:13).',
    'I am hungry for God. I am filled with the Holy Spirit and His power is upon me.',
    'Holy Spirit, fill me afresh today. I want more of You. Amen.', 'Spend ten minutes today praying and thanking God for the Holy Spirit.',
    [['What did Elisha ask for?', 'A double portion', 'Gold', 'A horse', 0], ['How did Elijah go to heaven?', 'In a whirlwind', 'On a boat', 'By walking', 0], ['What did Elisha strike the river with?', 'Elijah’s cloak', 'A stick', 'A sword', 0]],
    'ELISHA:He asked for a double portion|CLOAK:It fell from Elijah|DOUBLE:A ___ portion|WHIRLWIND:Took Elijah up|JORDAN:River that parted'],
  ['jonah-nineveh', 'Nineveh Says Sorry', 'Jonah 3–4', 'city', 'tree',
    ['After the big fish, Jonah finally went to Nineveh. He walked through the huge city crying, “In forty days Nineveh will be destroyed!”', 'Everyone, from the king to the poorest person, believed God. They stopped doing evil and prayed. God saw and had mercy on them.', 'Jonah was upset! He sat under a plant sulking. God taught him: “Should I not care about this great city?” God loves people everywhere.'],
    'The Lord is not slack concerning his promise… not willing that any should perish.', '2 Peter 3:9',
    'God loves everyone, even people we do not like.',
    'Jonah knew God’s Word but did not share God’s heart. God wants us to have His compassion. 2 Corinthians 5:18–19 says God has given us the ministry of reconciliation: telling the world that God is not counting their sins against them because of Jesus.',
    'I have God’s heart of compassion. I carry the message of reconciliation.',
    'Lord, give me Your love for people who don’t know You yet. Amen.', 'Pray for a country by name today.',
    [['How many days warning did Nineveh get?', 'Forty', 'Seven', 'Three', 0], ['What did the people do?', 'Laughed', 'Repented', 'Ran', 1], ['How did Jonah feel?', 'Happy', 'Upset', 'Sleepy', 1]],
    'NINEVEH:The great city|JONAH:Reluctant prophet|MERCY:God showed it|FORTY:Days of warning|SORRY:Nineveh said it'],
  ['esther-fast', 'Esther Goes to the King', 'Esther 4–5', 'palace', 'crown',
    ['Wicked Haman made a plan to destroy all the Jews. Mordecai told Queen Esther, “Who knows if you have come to the kingdom for such a time as this?”', 'But anyone who went to the king uninvited could be put to death! Esther asked all the Jews to fast and pray with her for three days.', 'Then Esther put on her royal robes and went in. The king held out his golden sceptre: “What is your request? Up to half my kingdom!”'],
    'Who knoweth whether thou art come to the kingdom for such a time as this?', 'Esther 4:14',
    'Prayer first, then boldness.',
    'Esther found favour after prayer and fasting. Hebrews 4:16 tells you to come boldly to the throne of grace. You do not need to be afraid of your King; through Jesus the sceptre is always held out to you. You are welcome in His presence.',
    'I come boldly to the throne of grace. I have favour with God and people.',
    'Father, thank You that I can always come to You. Amen.', 'Ask your family to pray together for one important thing this week.',
    [['How long did they fast?', 'Three days', 'Forty days', 'One week', 0], ['What did the king hold out?', 'A golden sceptre', 'A sword', 'A crown', 0], ['Who said “for such a time as this”?', 'Mordecai', 'Haman', 'The king', 0]],
    'ESTHER:The brave queen|SCEPTRE:Held out by the king|FAST:Esther called one|BOLD:Come ___ly to the throne|MORDECAI:Esther’s cousin'],
  ['daniel-dreams', 'Daniel and the Dream', 'Daniel 2', 'palace', 'scroll',
    ['King Nebuchadnezzar had a troubling dream. He demanded his wise men tell him both the dream and its meaning, or else!', 'No one could. Daniel asked for time and gathered his friends to pray. That night God showed Daniel the secret in a vision.', 'Daniel told the king the dream of a great statue and a stone that became a mountain. “There is a God in heaven who reveals secrets,” he said. The king honoured Daniel and his God.'],
    'There is a God in heaven that revealeth secrets.', 'Daniel 2:28',
    'God gives wisdom to those who ask Him.',
    'The stone cut without hands is a picture of Jesus and His kingdom, which will fill the whole earth. Daniel did not take credit; he pointed to God. 1 Corinthians 2:10 says God reveals deep things to us by His Spirit.',
    'The Holy Spirit reveals secrets to me. I give God all the glory.',
    'Lord, give me wisdom and understanding in my studies. Amen.', 'Before studying today, ask the Holy Spirit to help you understand.',
    [['What did the king want told?', 'The dream and meaning', 'A story', 'A joke', 0], ['What did Daniel do first?', 'Prayed with friends', 'Ran away', 'Slept', 0], ['What became a mountain?', 'A stone', 'A tree', 'A cloud', 0]],
    'DREAM:The king had one|SECRETS:God reveals them|STONE:Became a mountain|STATUE:Seen in the dream|VISION:How God showed Daniel'],
  ['habakkuk', 'Though the Fig Tree', 'Habakkuk 3:17–19', 'field', 'tree',
    ['The prophet Habakkuk looked around. The fig trees had no fruit, the vines no grapes, the fields no food, and the sheep pens were empty.', 'It looked very bad. But Habakkuk made a choice. He said, “Yet I will rejoice in the Lord. I will be joyful in the God of my salvation!”', '“The Lord God is my strength. He makes my feet like a deer’s, and He makes me walk on high places.”'],
    'Yet I will rejoice in the LORD, I will joy in the God of my salvation.', 'Habakkuk 3:18',
    'Joy is a choice you make because of who God is.',
    'Joy is a fruit of the Spirit (Galatians 5:22), not a feeling that depends on circumstances. It comes from inside you, from the Holy Spirit. Nehemiah 8:10 says the joy of the Lord is your strength. When you choose joy, you choose strength.',
    'The joy of the Lord is my strength. I rejoice in God at all times.',
    'Lord, I choose joy today because You are good. Amen.', 'Find something to be joyful about even if your day is hard.',
    [['What did the fig tree not have?', 'Leaves', 'Fruit', 'Roots', 1], ['What did Habakkuk choose?', 'To rejoice', 'To complain', 'To sleep', 0], ['God makes his feet like a…', 'Deer’s', 'Lion’s', 'Fish’s', 0]],
    'FIG:A tree with no fruit|REJOICE:Yet I will ___|JOY:A fruit of the Spirit|DEER:Sure-footed animal|STRENGTH:The Lord is my ___'],
  ['ezra-word', 'The People Hear the Word', 'Nehemiah 8', 'city', 'scroll',
    ['When the wall was finished, all the people gathered in a square. Ezra the scribe stood on a high wooden platform holding the Book of the Law.', 'When he opened it, everyone stood up. Ezra read from morning until noon, and teachers explained the meaning so everyone understood.', 'The people wept when they heard God’s Word. Nehemiah said, “Do not be sad. The joy of the Lord is your strength!” They went home to celebrate.'],
    'The joy of the LORD is your strength.', 'Nehemiah 8:10',
    'Understanding God’s Word brings joy and strength.',
    'They stood for the Word: that is honour. When the meaning was explained, their hearts changed. The Word is not just a book to read; it is God speaking. When you understand it, it builds your faith (Romans 10:17) and makes you strong.',
    'I honour God’s Word. As I understand it, my faith grows and I am strong.',
    'Lord, help me to understand Your Word. Amen.', 'Read a chapter of the Bible with your family and talk about it.',
    [['Who read the Book?', 'Ezra', 'David', 'Moses', 0], ['What did the people do when he opened it?', 'Stood up', 'Left', 'Laughed', 0], ['The joy of the Lord is your…', 'Song', 'Strength', 'Secret', 1]],
    'EZRA:The scribe who read|SCROLL:The Law was written on one|STAND:The people did it|JOY:___ of the Lord|EXPLAIN:The teachers did it'],
];

export const MORE2 = RAW.map(mk);
