import { mk, type Raw } from './mk';

// Jesus' ministry continued, and the early church. Verses are KJV.
const RAW: Raw[] = [
  ['man-born-blind', 'I Was Blind, Now I See', 'John 9', 'city', 'lamp',
    ['Jesus saw a man who had been blind since birth. The disciples asked, “Who sinned, this man or his parents?” Jesus said, “Neither. This happened so the works of God can be seen.”', 'Jesus made mud, put it on the man’s eyes and said, “Go wash in the pool of Siloam.” He went, washed and came back seeing!', 'The leaders questioned him angrily. He said, “One thing I know: I was blind, but now I see!” Later he met Jesus again and worshipped Him.'],
    'One thing I know, that, whereas I was blind, now I see.', 'John 9:25',
    'You don’t have to know everything to tell what Jesus did for you.',
    'Jesus refused to blame anyone. He came to reveal the works of God, not to condemn. The man’s testimony was simple and powerful. Your personal story of what Jesus has done for you is something no one can argue with.',
    'I was blind, but now I see. My testimony glorifies Jesus.',
    'Jesus, open my eyes to see You more. Amen.', 'Share your testimony of something God has done for you.',
    [['How long had the man been blind?', 'Since birth', 'One year', 'A week', 0], ['Where did he wash?', 'The pool of Siloam', 'The sea', 'A well', 0], ['What one thing did he know?', 'I was blind, now I see', 'Jesus is a sinner', 'Nothing', 0]],
    'SILOAM:The pool where he washed|MUD:Put on his eyes|BLIND:Since birth|SEE:Now I ___|WORKS:The ___ of God revealed'],
  ['good-shepherd', 'The Good Shepherd', 'John 10:1–18', 'field', 'staff',
    ['Jesus said, “I am the Good Shepherd. My sheep hear My voice. I know them, and they follow Me.”', '“A thief comes only to steal, kill and destroy. But I have come that they might have life, and have it more abundantly.”', '“The Good Shepherd gives His life for the sheep. No one can snatch them out of My hand.”'],
    'I am come that they might have life, and that they might have it more abundantly.', 'John 10:10',
    'Jesus knows your name and keeps you safe in His hand.',
    'John 10:10 shows the difference clearly: what steals, kills and destroys is from the thief; abundant life is from Jesus. You are safe in two hands: the Son’s and the Father’s (John 10:28–29). Abundant life means God’s life overflowing in every part of you.',
    'I have abundant life. I hear my Shepherd’s voice and no one can snatch me from His hand.',
    'Good Shepherd, lead me and keep me close. Amen.', 'Read Psalm 23 and draw a picture of it.',
    [['What do the sheep know?', 'The Shepherd’s voice', 'The way to town', 'Nothing', 0], ['What does the thief do?', 'Steal, kill, destroy', 'Help', 'Heal', 0], ['What did Jesus come to give?', 'Abundant life', 'Rules', 'Fear', 0]],
    'SHEPHERD:Jesus is the Good ___|SHEEP:They hear His voice|VOICE:The sheep know it|ABUNDANT:Life more ___|HAND:No one can snatch you out of it'],
  ['vine', 'The Vine and the Branches', 'John 15:1–8', 'garden', 'tree',
    ['On His last night with the disciples, Jesus pointed to a grapevine. “I am the vine, you are the branches.”', '“A branch cannot grow fruit by itself. It must stay joined to the vine. If you abide in Me and My words abide in you, you will bear much fruit.”', '“Without Me you can do nothing. But when you stay in Me, you can ask what you will, and it shall be done.”'],
    'I am the vine, ye are the branches.', 'John 15:5',
    'Stay connected to Jesus and fruit grows naturally.',
    'A branch does not strain to produce grapes; it simply stays connected and the life of the vine flows through it. You share the very life of Jesus. Abiding means staying in His Word and fellowship. The fruit of the Spirit (love, joy, peace…) grows out of that union.',
    'I am a branch in the Vine. His life flows through me and I bear much fruit.',
    'Jesus, help me stay close to You every day. Amen.', 'Name the fruit of the Spirit (Galatians 5:22–23) and choose one to show today.',
    [['Who is the vine?', 'Jesus', 'Peter', 'Moses', 0], ['What are we?', 'Branches', 'Leaves', 'Roots', 0], ['What can we do without Him?', 'Nothing', 'Everything', 'A little', 0]],
    'VINE:Jesus is the ___|BRANCHES:We are the ___|FRUIT:What branches bear|ABIDE:Stay in Him|GRAPES:Fruit of a vine'],
  ['peter-restored', 'Breakfast on the Beach', 'John 21:1–19', 'sea', 'fish',
    ['After Jesus rose, Peter went fishing. He had denied Jesus three times and felt like a failure. All night they caught nothing.', 'At dawn, a Man on the shore said, “Throw your net on the right side.” They caught 153 big fish! John said, “It is the Lord!” Peter jumped into the water to get to Him.', 'Jesus had made breakfast on a fire. Then He asked Peter three times, “Do you love Me?” Three times Peter said yes. Jesus said, “Feed My sheep.”'],
    'Lord, thou knowest all things; thou knowest that I love thee.', 'John 21:17',
    'Failure is not final with Jesus.',
    'Peter denied Jesus three times; Jesus restored him with three questions. Jesus did not lecture him; He fed him and gave him a mission. Weeks later at Pentecost, Peter preached and three thousand were saved. God’s grace restores and recommissions.',
    'Failure is not final. Jesus restores me, and I have a mission.',
    'Jesus, I love You. Thank You for always giving me another chance. Amen.', 'Forgive yourself for a mistake today, the way Jesus forgives you.',
    [['How many fish did they catch?', '153', '12', '1000', 0], ['What did Jesus cook?', 'Breakfast', 'Dinner', 'Nothing', 0], ['What did Jesus ask Peter?', 'Do you love Me?', 'Why did you fail?', 'Where were you?', 0]],
    'PETER:He was restored|BREAKFAST:Jesus cooked it|SHORE:Jesus stood there|LOVE:Do you ___ Me|SHEEP:Feed My ___'],
  ['ascension', 'Jesus Goes Up to Heaven', 'Acts 1:1–11', 'mountain', 'dove',
    ['For forty days after He rose, Jesus appeared to His followers and taught them. Then He said, “Wait in Jerusalem for the promise of the Father.”', '“You shall receive power when the Holy Spirit comes upon you, and you shall be My witnesses to the ends of the earth.”', 'Then He rose up into the sky and a cloud hid Him. Two angels said, “This same Jesus will come back in the same way!”'],
    'But ye shall receive power, after that the Holy Ghost is come upon you.', 'Acts 1:8',
    'Jesus went to heaven, but He did not leave us alone.',
    'Jesus is now seated at the right hand of the Father, and in Christ you are seated with Him (Ephesians 2:6). He sent the Holy Spirit to live in you, so it is better for you that He went (John 16:7). And He is coming back.',
    'I have received power by the Holy Ghost. I am a witness for Jesus.',
    'Jesus, thank You for sending the Holy Spirit. Fill me with power. Amen.', 'Tell someone that Jesus is coming back.',
    [['How long was Jesus on earth after rising?', 'Forty days', 'Three days', 'A year', 0], ['What did He promise?', 'Power from the Holy Spirit', 'Gold', 'A kingdom on earth', 0], ['What did the angels say?', 'He will come back', 'Go home', 'He is gone forever', 0]],
    'POWER:You shall receive ___|WITNESS:What we are|CLOUD:Hid Jesus|HEAVEN:Jesus went there|RETURN:Jesus will ___'],
  ['pentecost', 'The Holy Spirit Comes', 'Acts 2', 'city', 'dove',
    ['The disciples were praying together in Jerusalem. Suddenly a sound like a rushing mighty wind filled the house!', 'Tongues like fire sat on each of them. They were all filled with the Holy Ghost and began to speak in other tongues as the Spirit gave them words.', 'Crowds from many countries heard them praising God in their own languages! Peter stood up and preached, and three thousand people believed in Jesus that day.'],
    'And they were all filled with the Holy Ghost.', 'Acts 2:4',
    'The Holy Spirit makes ordinary people bold for Jesus.',
    'Peter, who was afraid before, became bold. The Holy Spirit is not a power you use; He is a Person who lives in you. Speaking in tongues is a gift for every believer (Acts 2:39), a way to pray with your spirit and build yourself up (Jude 20).',
    'I am filled with the Holy Ghost. I am bold, and I pray in the Spirit.',
    'Holy Spirit, fill me afresh and make me bold for Jesus. Amen.', 'Pray today and ask the Holy Spirit to fill you.',
    [['What did the sound sound like?', 'A rushing wind', 'Thunder', 'A trumpet', 0], ['What sat on each of them?', 'Tongues like fire', 'Doves', 'Crowns', 0], ['How many believed that day?', 'Three thousand', 'Twelve', 'One hundred', 0]],
    'PENTECOST:The day the Spirit came|WIND:A rushing mighty ___|FIRE:Tongues like ___|TONGUES:They spoke in other ___|BOLD:The Spirit makes us ___'],
  ['beautiful-gate', 'Silver and Gold Have I None', 'Acts 3:1–10', 'temple', 'staff',
    ['Peter and John went to the temple to pray. At the gate called Beautiful sat a man who had never walked. He asked them for money.', 'Peter looked at him: “Silver and gold have I none, but such as I have give I thee. In the name of Jesus Christ of Nazareth, rise up and walk!”', 'Peter took his hand and lifted him. His feet and ankles became strong! He jumped up and went into the temple walking, leaping and praising God!'],
    'Such as I have give I thee: In the name of Jesus Christ of Nazareth rise up and walk.', 'Acts 3:6',
    'You have something better than money to give: Jesus.',
    'Peter knew what he had: the name of Jesus and the power of the Spirit. Many believers do not know what they have. Philemon 6 says your faith becomes effective as you acknowledge every good thing in you in Christ. Know what you carry.',
    'I know what I have in Christ. I give what I have: the name and power of Jesus.',
    'Jesus, help me know what I carry and share it. Amen.', 'Pray for someone today, using the name of Jesus.',
    [['What was the gate called?', 'Beautiful', 'Golden', 'Royal', 0], ['What did Peter not have?', 'Silver and gold', 'Faith', 'Friends', 0], ['What did the man do?', 'Walked and leaped', 'Sat still', 'Ran away', 0]],
    'BEAUTIFUL:The name of the gate|SILVER:Peter had none|GOLD:Peter had none of this either|WALK:Rise up and ___|LEAPING:Walking and ___'],
  ['stephen', 'Stephen Sees Heaven Open', 'Acts 6–7', 'city', 'crown',
    ['Stephen was full of faith and power, and did great wonders. His enemies could not argue against the wisdom and Spirit by which he spoke.', 'They brought him to court. While they accused him, his face shone like an angel’s! Stephen boldly told them about Jesus.', 'As they threw stones, Stephen looked up and saw heaven open and Jesus standing at God’s right hand. He prayed, “Lord, do not hold this sin against them.”'],
    'Lord, lay not this sin to their charge.', 'Acts 7:60',
    'The Holy Spirit gives courage and love, even toward enemies.',
    'Stephen forgave like Jesus did on the cross. His name means “crown”. Among those watching was a young man called Saul, who later became Paul. Stephen’s love and courage were a seed. Your faithfulness may affect people you never expect.',
    'I am full of faith and the Holy Ghost. I love and forgive like Jesus.',
    'Lord, give me courage to stand for You and love to forgive. Amen.', 'Pray for Christians in countries where it is hard to follow Jesus.',
    [['What was Stephen full of?', 'Faith and power', 'Fear', 'Anger', 0], ['What did his face look like?', 'An angel’s', 'Angry', 'Sad', 0], ['Who was watching?', 'Saul', 'Peter', 'Herod', 0]],
    'STEPHEN:Full of faith and power|ANGEL:His face shone like one|HEAVEN:He saw it open|FORGIVE:Stephen did it|SAUL:Watched it happen'],
  ['ethiopian', 'Philip and the Chariot', 'Acts 8:26–40', 'desert', 'scroll',
    ['An angel told Philip, “Go south to the desert road.” There he saw an important official from Ethiopia, riding in a chariot and reading the book of Isaiah.', 'The Spirit said, “Go join that chariot.” Philip ran up and asked, “Do you understand what you are reading?” “How can I, unless someone explains it?”', 'Philip explained that Isaiah was writing about Jesus. The man believed and said, “Here is water! Can I be baptised?” He went home to Africa rejoicing!'],
    'Then Philip opened his mouth… and preached unto him Jesus.', 'Acts 8:35',
    'The Holy Spirit leads us to people who are ready to hear about Jesus.',
    'Philip obeyed the Spirit’s leading without knowing why. The Spirit knows who is hungry for God. The gospel went to Africa very early in church history through this man. Be sensitive to the Spirit’s prompting; He may send you to one person who needs Jesus.',
    'I am led by the Spirit. He gives me divine appointments to share Jesus.',
    'Holy Spirit, lead me to someone who needs Jesus. Amen.', 'Ask the Holy Spirit who you should encourage today, and do it.',
    [['What was the official reading?', 'Isaiah', 'Genesis', 'Psalms', 0], ['Where was he from?', 'Ethiopia', 'Rome', 'Egypt', 0], ['What did he ask for?', 'Baptism', 'Money', 'A ride', 0]],
    'PHILIP:He ran to the chariot|CHARIOT:The official rode in it|ETHIOPIA:The man’s country|ISAIAH:The book he read|BAPTISM:He asked for it'],
  ['saul-converted', 'Saul Meets Jesus', 'Acts 9:1–22', 'desert', 'sun',
    ['Saul hated Christians. He was on the road to Damascus to arrest them. Suddenly a light from heaven, brighter than the sun, flashed around him and he fell.', 'A voice said, “Saul, Saul, why do you persecute Me?” “Who are You, Lord?” “I am Jesus.” Saul got up blind and was led into the city.', 'God sent Ananias to pray for him. Something like scales fell from Saul’s eyes; he could see! He was baptised and began preaching about Jesus. He became the apostle Paul.'],
    'If any man be in Christ, he is a new creature.', '2 Corinthians 5:17',
    'Nobody is too far away for Jesus to reach.',
    'Jesus said, “Why do you persecute Me?” Jesus is so united with His people that what is done to them is done to Him. Paul went on to write much of the New Testament, revealing what it means to be “in Christ”. Pray for the hardest people you know; God can change anyone.',
    'I am a new creature in Christ. Jesus can reach anyone, and He uses me.',
    'Lord, I pray for people who seem far from You. Reach them. Amen.', 'Pray for someone who is unkind to Christians.',
    [['Where was Saul going?', 'Damascus', 'Egypt', 'Bethlehem', 0], ['What knocked him down?', 'A light from heaven', 'A horse', 'A storm', 0], ['What name did Saul later have?', 'Paul', 'Peter', 'Philip', 0]],
    'SAUL:Later called Paul|DAMASCUS:The road he travelled|LIGHT:Brighter than the sun|ANANIAS:Prayed for Saul|SCALES:Fell from his eyes'],
  ['dorcas', 'Dorcas, Full of Good Works', 'Acts 9:36–42', 'city', 'gift',
    ['In Joppa lived Dorcas, who loved Jesus. She was always doing kind things, especially making coats and clothes for widows and poor people.', 'Dorcas became sick and died. Her friends were heartbroken. They sent for Peter, and the widows showed him all the clothes she had made.', 'Peter knelt and prayed, then said, “Tabitha, arise.” She opened her eyes and sat up! News spread everywhere, and many believed in the Lord.'],
    'This woman was full of good works and almsdeeds.', 'Acts 9:36',
    'Kindness that serves others leaves a beautiful mark.',
    'Peter did what he had seen Jesus do with Jairus’ daughter, almost word for word. Believers continue the works of Jesus (John 14:12). Dorcas also shows that a life of love and practical service is real ministry.',
    'I do the works of Jesus. I am full of good works and kindness.',
    'Lord, help me to be full of good works like Dorcas. Amen.', 'Make or give something to help someone in need.',
    [['What did Dorcas make?', 'Clothes', 'Bread', 'Pottery', 0], ['Who prayed for her?', 'Peter', 'Paul', 'John', 0], ['What did Peter say?', 'Tabitha, arise', 'Goodbye', 'Sleep well', 0]],
    'DORCAS:Full of good works|COATS:She made them|WIDOWS:She helped them|ARISE:Tabitha, ___|JOPPA:Her town'],
  ['peter-prison', 'Peter’s Midnight Escape', 'Acts 12:1–17', 'night', 'lamp',
    ['King Herod threw Peter into prison, chained between two soldiers. But the church prayed for him without stopping.', 'That night, an angel appeared and a light shone in the cell. “Get up quickly!” The chains fell off Peter’s hands! He followed the angel past the guards, and the iron gate opened by itself.', 'Peter went to the house where they were praying and knocked. A girl called Rhoda was so excited she forgot to open the door!'],
    'Prayer was made without ceasing of the church unto God for him.', 'Acts 12:5',
    'When God’s people pray together, prison doors open.',
    'Peter was sleeping peacefully the night before his trial: that is rest in God. The church’s prayer released angelic help. United prayer is powerful (Matthew 18:19). Do not underestimate your prayers for others.',
    'When I pray, chains break and doors open. I rest in God’s peace.',
    'Lord, I pray for those who need breakthrough today. Amen.', 'Join with your family to pray for someone in trouble.',
    [['Who put Peter in prison?', 'Herod', 'Pharaoh', 'Pilate', 0], ['What fell off Peter?', 'His chains', 'His shoes', 'His cloak', 0], ['Who answered the door?', 'Rhoda', 'Mary', 'John', 0]],
    'PETER:He escaped prison|CHAINS:They fell off|ANGEL:Led him out|RHODA:Forgot to open the door|PRAYER:Made without ceasing'],
  ['paul-silas', 'Songs at Midnight', 'Acts 16:16–34', 'night', 'harp',
    ['Paul and Silas were beaten and thrown into the deepest prison with their feet in stocks. It was dark and painful.', 'But at midnight they prayed and sang praises to God, and the other prisoners listened! Suddenly a great earthquake shook the prison. All the doors opened and everyone’s chains fell off!', 'The jailer was terrified. “What must I do to be saved?” “Believe on the Lord Jesus Christ, and you shall be saved, and your house.” He and his whole family believed that night.'],
    'Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house.', 'Acts 16:31',
    'Praise in the dark brings God’s power.',
    'Paul and Silas praised before release. The joy of the Lord in them was stronger than the prison. Their praise freed everyone, not just themselves, and led to a whole family being saved. Your praise in hard times can affect people around you.',
    'I praise God at midnight. My praise sets me and others free.',
    'Lord, I will praise You even when things are hard. Amen.', 'Sing a worship song before you sleep tonight.',
    [['What did Paul and Silas do at midnight?', 'Prayed and sang', 'Slept', 'Cried', 0], ['What shook the prison?', 'An earthquake', 'A storm', 'An army', 0], ['Who got saved?', 'The jailer and his family', 'Nobody', 'The king', 0]],
    'SILAS:Paul’s partner|MIDNIGHT:When they sang|CHAINS:They fell off everyone|JAILER:He got saved|PRAISE:Sing it in the dark'],
  ['lydia', 'Lydia Opens Her Heart', 'Acts 16:11–15', 'river', 'gift',
    ['In Philippi there was no synagogue, so on the Sabbath, Paul went to a riverside where people prayed.', 'He met Lydia, a businesswoman who sold expensive purple cloth. As Paul spoke, the Lord opened her heart, and she believed in Jesus.', 'She and her household were baptised. Then she said, “Come and stay at my house.” Her home became the first church meeting place in Europe!'],
    'Whose heart the Lord opened.', 'Acts 16:14',
    'God opens hearts, and an open heart opens its home.',
    'Lydia used her business and her house for God’s kingdom. Your gifts, skills and future work can all serve the gospel. Hospitality is a ministry (Romans 12:13). The first church in Europe started from one open heart.',
    'My heart is open to God. I use everything I have for His kingdom.',
    'Lord, open my heart to Your Word and help me serve You with all I have. Amen.', 'Welcome someone into your home or group this week.',
    [['Where did Paul meet Lydia?', 'By a river', 'In a temple', 'At sea', 0], ['What did Lydia sell?', 'Purple cloth', 'Fish', 'Bread', 0], ['What did she open for Paul?', 'Her home', 'A school', 'A shop', 0]],
    'LYDIA:Seller of purple|PURPLE:Expensive cloth colour|RIVER:Where people prayed|HEART:The Lord opened it|HOME:She opened hers'],
  ['eutychus', 'The Boy Who Fell Asleep', 'Acts 20:7–12', 'city', 'lamp',
    ['Paul was preaching in an upstairs room with many lamps. He talked until midnight because he was leaving the next day.', 'A young man named Eutychus sat on the windowsill. He got sleepier and sleepier, and fell asleep and fell three floors down! He was picked up dead.', 'Paul ran down, hugged him and said, “Do not be troubled, his life is in him.” Eutychus was alive! Everyone was greatly comforted, and Paul kept teaching till dawn.'],
    'Trouble not yourselves; for his life is in him.', 'Acts 20:10',
    'God’s life is stronger than any accident.',
    'Paul spoke life over Eutychus. The life of God in a believer is not fragile. It is “zoe”, eternal life (1 John 5:11–12). You can expect God’s protection and life in your body. And yes, God has a sense of humour about sleepy listeners too.',
    'The life of God is in me. I am protected, and I speak life.',
    'Thank You, Lord, that Your life is in me. Amen.', 'Stay alert in church this Sunday and write down one thing you learn.',
    [['Where did Eutychus sit?', 'On a windowsill', 'On the floor', 'On the roof', 0], ['What happened?', 'He fell asleep and fell', 'He sang', 'He left', 0], ['What did Paul say?', 'His life is in him', 'It is over', 'Go home', 0]],
    'EUTYCHUS:The sleepy boy|WINDOW:He sat in it|MIDNIGHT:Paul preached until then|LIFE:His ___ is in him|ASLEEP:What he fell'],
  ['shipwreck', 'Paul’s Shipwreck', 'Acts 27', 'storm', 'boat',
    ['Paul was on a ship to Rome when a terrible storm hit. For days there was no sun and no stars. Everyone gave up hope.', 'Paul stood up: “Be of good cheer! An angel of God told me that no one will die. I believe God that it will be just as He told me.”', 'The ship hit a sandbank and broke apart, but every person, all 276, got safely to land, just as Paul said!'],
    'Wherefore, sirs, be of good cheer: for I believe God, that it shall be even as it was told me.', 'Acts 27:25',
    'One person who believes God can bring hope to everyone.',
    'Paul was a prisoner, yet he became the leader on the ship. Faith makes you a leader in a crisis. “I believe God” is the simplest confession of faith. Everyone on the ship was saved because of one believer’s faith.',
    'I believe God, that it shall be even as He told me. I bring hope in every storm.',
    'Lord, I believe You. Help me bring hope to people around me. Amen.', 'Encourage someone who is worried today.',
    [['Where was the ship going?', 'Rome', 'Egypt', 'Jerusalem', 0], ['Who told Paul no one would die?', 'An angel', 'The captain', 'A soldier', 0], ['How many were saved?', 'All 276', 'Half', 'Only Paul', 0]],
    'PAUL:The prisoner with faith|STORM:Lasted many days|SHIP:It broke apart|CHEER:Be of good ___|ROME:Their destination'],
  ['malta-snake', 'The Snake on Paul’s Hand', 'Acts 28:1–10', 'sea', 'lamp',
    ['After the shipwreck, everyone landed on the island of Malta. The people were kind and built a fire because it was cold and raining.', 'Paul gathered sticks for the fire. A poisonous snake came out from the heat and bit his hand! The islanders waited for him to swell up and die.', 'Paul just shook it off into the fire and was fine! Then Paul prayed for the island’s sick people, and they were all healed.'],
    'They shall take up serpents… it shall not hurt them.', 'Mark 16:18',
    'Shake off what the enemy throws at you.',
    'Paul did not panic; he shook it off. Jesus promised believers protection (Mark 16:18; Luke 10:19). This is not about testing God by playing with danger, but about trusting His protection when attacks come. Then the attack turned into an open door for ministry.',
    'Nothing shall by any means hurt me. I shake off every attack of the enemy.',
    'Lord, thank You for Your protection. Amen.', 'Shake off a hurtful word someone said, and forgive them.',
    [['What island were they on?', 'Malta', 'Crete', 'Cyprus', 0], ['What bit Paul?', 'A snake', 'A dog', 'A spider', 0], ['What did Paul do?', 'Shook it off', 'Cried', 'Ran', 0]],
    'MALTA:The island|SNAKE:It bit Paul|FIRE:Paul shook it into this|SHAKE:___ it off|HEALED:The sick on the island'],
  ['timothy', 'Young Timothy', '2 Timothy 1:5; 3:14–15', 'city', 'scroll',
    ['Timothy grew up with a grandmother named Lois and a mother named Eunice who loved God. They taught him the Scriptures from when he was a little child.', 'When Paul visited, he saw that Timothy had a sincere faith. He took Timothy with him on his journeys, like a son.', 'Paul wrote to him, “Let no one look down on you because you are young. Be an example in what you say, how you live, in love, in faith and in purity.”'],
    'From a child thou hast known the holy scriptures.', '2 Timothy 3:15',
    'You are never too young to be an example.',
    'Timothy’s faith started at home. Paul told him to “stir up the gift of God” inside him (2 Timothy 1:6). Gifts can be stirred up by prayer, the Word and use. Your youth is not a weakness; it is a season to grow strong roots.',
    'I stir up the gift of God in me. I am an example of the believers.',
    'Lord, thank You for my family. Help me be an example. Amen.', 'Thank your parent, grandparent or guardian for teaching you about God.',
    [['Who was Timothy’s grandmother?', 'Lois', 'Mary', 'Ruth', 0], ['What did Timothy know from a child?', 'The Scriptures', 'Fishing', 'Building', 0], ['Who took Timothy on journeys?', 'Paul', 'Peter', 'John', 0]],
    'TIMOTHY:The young helper|LOIS:His grandmother|EUNICE:His mother|EXAMPLE:Be one|YOUNG:Do not let them despise you for it'],
  ['armour', 'The Armour of God', 'Ephesians 6:10–18', 'mountain', 'staff',
    ['Paul was chained to a Roman soldier. He looked at the soldier’s armour and thought about the Christian life.', '“Put on the whole armour of God: the belt of truth, the breastplate of righteousness, shoes of the gospel of peace, the shield of faith, the helmet of salvation and the sword of the Spirit, which is the Word of God.”', '“Be strong in the Lord and in the power of His might. Stand! And pray always in the Spirit.”'],
    'Be strong in the Lord, and in the power of his might.', 'Ephesians 6:10',
    'God has given you everything you need to stand strong.',
    'Our battle is not against people but spiritual forces (Ephesians 6:12). The armour is really Christ Himself: He is our truth, righteousness, peace and salvation. The shield of faith quenches all the fiery darts: lies, fears and temptations. The Word is your one attacking weapon.',
    'I am strong in the Lord. I wear the whole armour of God and I stand.',
    'Lord, I put on Your armour today. Amen.', 'Act out putting on each piece of armour and say what it is.',
    [['What is the sword of the Spirit?', 'The Word of God', 'Prayer', 'A real sword', 0], ['What quenches the fiery darts?', 'The shield of faith', 'The helmet', 'The shoes', 0], ['Who is our battle against?', 'Spiritual forces', 'People', 'Animals', 0]],
    'ARMOUR:The whole ___ of God|SHIELD:Of faith|HELMET:Of salvation|SWORD:Of the Spirit|STAND:What we do'],
  ['new-creation', 'Brand New!', '2 Corinthians 5:17–21', 'garden', 'dove',
    ['A caterpillar crawls slowly on a leaf. Then it makes a cocoon and comes out as a beautiful butterfly. It is not a better caterpillar; it is a new creature!', 'Paul wrote that when someone is in Christ, the same happens. The old life is gone. Everything is made new by God.', 'God made Jesus, who never sinned, to be sin for us, so that we could be made the righteousness of God in Him. That is the best exchange ever!'],
    'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.', '2 Corinthians 5:17',
    'In Christ you are not improved; you are brand new.',
    'Righteousness means right standing with God, as if sin had never been. It is not how good you feel; it is a gift (Romans 5:17). When you know you are righteous, you stop hiding from God and start reigning in life. This is the heart of the gospel.',
    'I am a new creature. I am the righteousness of God in Christ. I reign in life.',
    'Thank You, Father, for making me brand new in Jesus. Amen.', 'Draw a butterfly and write “I am a new creation” on it.',
    [['What does a caterpillar become?', 'A butterfly', 'A bird', 'A bee', 0], ['In Christ, what are we?', 'A new creature', 'The same as before', 'A little better', 0], ['What are we made in Him?', 'The righteousness of God', 'Perfect at sports', 'Rich', 0]],
    'NEW:All things are ___|CREATURE:A new ___|BUTTERFLY:Picture of new life|RIGHTEOUS:Right with God|CHRIST:We are in Him'],
  ['love-chapter', 'What Love Looks Like', '1 Corinthians 13', 'garden', 'gift',
    ['Paul wrote, “I could speak in every language, know every secret and have faith to move mountains, but if I do not have love, I am nothing.”', '“Love is patient and kind. Love is not jealous or proud. It does not keep a list of wrongs. It is happy with the truth.”', '“Love never fails. Faith, hope and love remain, but the greatest of these is love.”'],
    'Charity never faileth.', '1 Corinthians 13:8',
    'Love is the most important thing of all.',
    'God is love (1 John 4:8), and His love has been poured into your heart (Romans 5:5). So love is not something you produce; it is God’s nature in you. Faith works by love (Galatians 5:6). When you walk in love, your faith works.',
    'The love of God is in my heart. I am patient and kind. Love never fails in me.',
    'Lord, help Your love flow through me today. Amen.', 'Read 1 Corinthians 13:4–7 and put your name in place of “love”.',
    [['Without love, what are we?', 'Nothing', 'Strong', 'Famous', 0], ['Love is patient and…', 'Kind', 'Loud', 'Fast', 0], ['What is the greatest?', 'Love', 'Faith', 'Hope', 0]],
    'LOVE:The greatest|PATIENT:Love is ___|KIND:Love is ___|NEVER:Love ___ fails|CHARITY:KJV word for love'],
  ['heaven', 'All Things New', 'Revelation 21–22', 'city', 'crown',
    ['God showed John a vision of the future: a new heaven and a new earth, and a holy city coming down from God, shining like a precious jewel.', 'The city has streets of gold, gates of pearl and a river of life flowing from God’s throne. It needs no sun, because God’s glory gives it light.', 'God will live with His people. He will wipe away every tear. There will be no more crying, pain or death. Jesus says, “Behold, I make all things new.”'],
    'Behold, I make all things new.', 'Revelation 21:5',
    'The best is yet to come for everyone who belongs to Jesus.',
    'The Bible begins in a garden and ends in a city where God lives with His people forever. Eternal life is the life of God, which you already have, and one day you will see Him face to face. This hope keeps you joyful and pure (1 John 3:3).',
    'I have eternal life. The best is yet to come, and I will live with God forever.',
    'Jesus, thank You for the wonderful future You have prepared. Amen.', 'Draw what you think the holy city looks like.',
    [['What are the streets made of?', 'Gold', 'Stone', 'Sand', 0], ['What lights the city?', 'God’s glory', 'The sun', 'Lamps', 0], ['What will God wipe away?', 'Every tear', 'Every house', 'The stars', 0]],
    'HEAVEN:A new ___ and earth|GOLD:The streets|PEARL:The gates|RIVER:Of life|TEARS:God wipes them away'],
];

export const MORE4 = RAW.map(mk);
