import { mk, type Raw } from './mk';

// Life of Jesus. Verses are KJV.
const RAW: Raw[] = [
  ['john-baptist', 'John Prepares the Way', 'Matthew 3:1–12; John 1:29', 'river', 'dove',
    ['In the desert lived John the Baptist. He wore camel hair and ate locusts and wild honey. Crowds came to hear him by the Jordan River.', 'John said, “Turn back to God! Get ready, because the King is coming.” People confessed their sins, and John baptised them in the river.', 'One day John saw Jesus coming. He pointed and shouted, “Behold the Lamb of God, which taketh away the sin of the world!”'],
    'Behold the Lamb of God, which taketh away the sin of the world.', 'John 1:29',
    'John’s whole life pointed people to Jesus. Ours can too.',
    'John said, “He must increase, but I must decrease” (John 3:30). The goal of a Christian life is to make Jesus big. Jesus took away sin, not only covered it. When God looks at you now, He sees no sin record, because the Lamb took it away.',
    'My sins are taken away by the Lamb of God. My life points people to Jesus.',
    'Jesus, be bigger in my life every day. Amen.', 'Point someone to Jesus today with a kind word or your testimony.',
    [['What did John eat?', 'Locusts and honey', 'Bread and fish', 'Fruit', 0], ['Where did John baptise?', 'The Jordan River', 'The sea', 'A pool', 0], ['What did John call Jesus?', 'The Lamb of God', 'The Lion', 'The Teacher', 0]],
    'JOHN:The Baptist|LOCUSTS:John ate them|HONEY:Wild and sweet|LAMB:Behold the ___ of God|JORDAN:River of baptism'],
  ['baptism', 'Jesus Is Baptised', 'Matthew 3:13–17', 'river', 'dove',
    ['Jesus came to the Jordan to be baptised by John. John said, “I need You to baptise me!” But Jesus said, “Let us do what is right.”', 'When Jesus came up out of the water, heaven opened and the Spirit of God came down like a dove and rested on Him.', 'A voice from heaven said, “This is My beloved Son, in whom I am well pleased.” Father, Son and Holy Spirit were all there together!'],
    'This is my beloved Son, in whom I am well pleased.', 'Matthew 3:17',
    'God spoke His love over Jesus before Jesus had done a single miracle.',
    'You are accepted in the Beloved (Ephesians 1:6). In Christ, the Father says the same over you: beloved, pleasing. You do not work for His love; you work from it. Jesus also received the Holy Spirit before ministry. You need the Spirit too.',
    'I am a beloved child of God. My Father is well pleased with me in Christ.',
    'Father, thank You that You love me and I am Yours. Amen.', 'Look in the mirror and say, “I am God’s beloved child.”',
    [['Who baptised Jesus?', 'John', 'Peter', 'Moses', 0], ['How did the Spirit come?', 'Like a dove', 'Like fire', 'Like rain', 0], ['What did the Father say?', 'This is My beloved Son', 'Go away', 'Be careful', 0]],
    'BAPTISM:Jesus received it|DOVE:The Spirit came like one|BELOVED:My ___ Son|PLEASED:Well ___|SPIRIT:Came down from heaven'],
  ['temptation', 'It Is Written', 'Matthew 4:1–11', 'desert', 'scroll',
    ['The Holy Spirit led Jesus into the desert. He fasted forty days. Then the devil came to tempt Him: “If You are the Son of God, turn these stones into bread.”', 'Jesus answered, “It is written, man shall not live by bread alone.” The devil tried twice more. Each time Jesus said, “It is written.”', 'Finally Jesus said, “Get thee hence, Satan!” The devil left, and angels came and served Jesus.'],
    'Submit yourselves therefore to God. Resist the devil, and he will flee from you.', 'James 4:7',
    'The Word of God is your sword against temptation.',
    'Jesus did not argue with feelings; He used Scripture. The devil questioned His identity (“If You are the Son…”), but Jesus knew who He was. You defeat the devil the same way: knowing your identity and speaking the Word. That is why memorising Scripture matters.',
    'I resist the devil with the Word, and he flees from me. I know who I am.',
    'Lord, help me fill my heart with Your Word. Amen.', 'Memorise James 4:7 today.',
    [['How long did Jesus fast?', 'Forty days', 'Seven days', 'One day', 0], ['What did Jesus say each time?', 'It is written', 'No thanks', 'Go away', 0], ['Who came after the devil left?', 'Angels', 'Disciples', 'Soldiers', 0]],
    'WRITTEN:It is ___|DESERT:Where Jesus fasted|FORTY:Days of fasting|SWORD:The Word is one|RESIST:Do this to the devil'],
  ['water-wine', 'Water into Wine', 'John 2:1–11', 'city', 'jar',
    ['Jesus, His mother Mary and His disciples were at a wedding in Cana. Oh no, the wine ran out! That would be very embarrassing for the family.', 'Mary told the servants, “Whatever He says to you, do it.” Jesus said, “Fill the six stone jars with water.” They filled them to the brim.', '“Now take some to the master of the feast.” It was the best wine! This was Jesus’ first miracle, and His disciples believed in Him.'],
    'Whatsoever he saith unto you, do it.', 'John 2:5',
    'Obeying Jesus, even in small instructions, opens the way for miracles.',
    'Jesus’ first miracle was at a celebration. He cares about joy. The new wine is a picture of the new life of the Spirit: better than the old. Mary’s advice is the best advice ever: whatever He says, do it. Miracles follow obedience to His Word.',
    'Whatever Jesus says to me, I do. My life is full of His new wine.',
    'Jesus, I will do whatever You tell me. Amen.', 'Obey the first time you are asked today.',
    [['Where was the wedding?', 'Cana', 'Jerusalem', 'Nazareth', 0], ['What ran out?', 'Bread', 'Wine', 'Water', 1], ['What did Mary say?', 'Whatever He says, do it', 'Let’s go home', 'Buy more', 0]],
    'CANA:Town of the wedding|WEDDING:A celebration|WINE:Jesus made it from water|JARS:Six stone ones|OBEY:Whatever He says, do it'],
  ['nicodemus', 'You Must Be Born Again', 'John 3:1–17', 'night', 'lamp',
    ['Nicodemus was an important teacher. One night he secretly came to Jesus. “We know You come from God,” he said.', 'Jesus told him, “Unless a person is born again, he cannot see the kingdom of God.” Nicodemus asked, “How can a grown man be born again?”', 'Jesus explained that it is a spiritual birth by the Spirit of God, and then said the most famous words: “For God so loved the world, that He gave His only begotten Son.”'],
    'For God so loved the world, that he gave his only begotten Son.', 'John 3:16',
    'Being a Christian is not being religious. It is being born of God.',
    'When you believe in Jesus and confess Him as Lord (Romans 10:9–10), your spirit is born again: a brand-new creation with God’s life and nature in it. You are not just forgiven; you are recreated. This is the foundation of everything.',
    'I am born again. I have the life and nature of God in my spirit.',
    'Jesus, thank You for making me new. Amen.', 'Learn John 3:16 by heart and say it to someone.',
    [['When did Nicodemus come?', 'At night', 'At noon', 'At dawn', 0], ['What did Jesus say we must be?', 'Born again', 'Rich', 'Strong', 0], ['Complete it: For God so loved the…', 'Church', 'World', 'Angels', 1]],
    'NIGHT:When Nicodemus came|BORN:You must be ___ again|SPIRIT:We are born of it|LOVED:For God so ___ the world|SON:God gave His only ___'],
  ['woman-well', 'Living Water', 'John 4:1–42', 'desert', 'jar',
    ['Jesus was tired and sat by a well in Samaria. A woman came to draw water at noon, when nobody else was around. Jesus said, “Please give Me a drink.”', 'She was surprised: Jews did not speak to Samaritans! Jesus said, “Whoever drinks the water I give will never thirst again. It will be a spring of water inside them.”', 'Jesus knew all about her life, yet He offered her living water. She ran back to town: “Come and see a man who told me everything I ever did!” Many believed.'],
    'Whosoever drinketh of the water that I shall give him shall never thirst.', 'John 4:14',
    'Jesus satisfies the deepest thirst of your heart.',
    'The living water is the Holy Spirit (John 7:38–39). Jesus did not give her a lecture; He gave her an offer. A satisfied heart does not need to chase what the world offers. And notice: she immediately became an evangelist. You do not need to wait to share Jesus.',
    'Rivers of living water flow out of me. My heart is satisfied in Jesus.',
    'Jesus, You are all I need. Fill me with Your living water. Amen.', 'Invite someone to church or to a Bible club.',
    [['Where did Jesus meet the woman?', 'At a well', 'In the temple', 'On a boat', 0], ['What did Jesus offer?', 'Living water', 'Money', 'Bread', 0], ['What did she do after?', 'Told her town', 'Hid', 'Went to sleep', 0]],
    'WELL:Jesus sat by it|WATER:Living ___|SAMARIA:The woman’s country|THIRST:Never again|SPRING:Water inside you'],
  ['nobleman', 'Go, Your Son Lives', 'John 4:46–54', 'city', 'sun',
    ['A royal official’s son was very sick, almost dying. The man travelled to Jesus and begged, “Sir, come down before my child dies!”', 'Jesus said, “Go your way. Your son lives.” The man believed the word Jesus spoke and started home, without Jesus coming with him.', 'On the way his servants ran to meet him: “Your son is alive!” The fever left at one o’clock, exactly when Jesus had spoken.'],
    'He sent his word, and healed them.', 'Psalm 107:20',
    'The word of Jesus is enough. You can believe it before you see it.',
    'The man had to believe the word alone, with no sign. That is how we live today: Jesus is not physically here, but His Word is. The Word carries the same power as His presence. Faith takes God at His Word and acts on it.',
    'I believe God’s Word before I see it. His Word is enough for me.',
    'Lord, help me believe Your Word even when I cannot see. Amen.', 'Pray for someone who is sick and believe God’s Word for them.',
    [['Who was sick?', 'The official’s son', 'His wife', 'His servant', 0], ['Did Jesus go to the house?', 'Yes', 'No, He sent His word', 'He sent an angel', 1], ['When did the fever leave?', 'When Jesus spoke', 'The next day', 'A week later', 0]],
    'FEVER:It left at one o’clock|WORD:Jesus sent it|BELIEVE:The man did|SON:He was healed|LIVES:Your son ___'],
  ['fishers', 'Fishers of Men', 'Luke 5:1–11', 'sea', 'fish',
    ['Peter had fished all night and caught nothing. Jesus borrowed his boat to teach the crowd, then said, “Go out deeper and let down your nets.”', 'Peter said, “Master, we have toiled all night and caught nothing, nevertheless at Thy word I will let down the net.” They caught so many fish the nets began to break!', 'Peter fell at Jesus’ knees. Jesus said, “Do not fear. From now on you will catch men.” They left everything and followed Him.'],
    'Nevertheless at thy word I will let down the net.', 'Luke 5:5',
    'Your experience says one thing; Jesus’ word says another. Choose His word.',
    '“At Thy word” turned a night of failure into overflow. Faith acts on what God says over what experience says. And Jesus did not just bless Peter’s business; He gave him a bigger purpose: winning souls. Every believer is called to be a soul winner.',
    'At His word I act. I am a fisher of men and I win souls for Jesus.',
    'Jesus, I will follow You. Use me to bring others to You. Amen.', 'Pray for three friends who do not know Jesus yet.',
    [['How long had Peter fished?', 'All night', 'One hour', 'A week', 0], ['What happened to the nets?', 'They broke from so many fish', 'They were empty', 'They floated away', 0], ['What did Jesus call them to catch?', 'Men', 'Birds', 'Bigger fish', 0]],
    'PETER:The fisherman|NETS:They began to break|FISH:Caught by the boatful|DEEP:Go out into the ___|FOLLOW:They left all to ___ Him'],
  ['through-roof', 'Friends Through the Roof', 'Mark 2:1–12', 'city', 'lamp',
    ['A house was packed with people listening to Jesus. Four friends carried a man who could not walk, but they could not get in.', 'So they climbed onto the roof, dug a hole and lowered their friend down on his mat, right in front of Jesus!', 'Jesus saw their faith and said, “Son, your sins are forgiven. Get up, take your mat and walk.” The man jumped up and walked out while everyone praised God!'],
    'When Jesus saw their faith…', 'Mark 2:5',
    'Faith finds a way, and good friends bring you to Jesus.',
    'Jesus saw their faith: faith is visible; it acts. The man needed forgiveness and healing, and Jesus gave both. Healing and forgiveness come together in the gospel (Psalm 103:3). Be the kind of friend who carries others to Jesus in prayer.',
    'My faith acts. I carry my friends to Jesus in prayer.',
    'Lord, give me faith that doesn’t give up. Amen.', 'Bring a friend’s need to Jesus in prayer today.',
    [['How many friends carried the man?', 'Two', 'Four', 'Ten', 1], ['How did they get in?', 'Through the roof', 'Through a window', 'Through a door', 0], ['What did Jesus see?', 'Their faith', 'Their money', 'Their tears', 0]],
    'ROOF:They dug through it|MAT:The man lay on it|FRIENDS:Four of them|FAITH:Jesus saw it|WALK:Get up and ___'],
  ['centurion', 'Just Say the Word', 'Matthew 8:5–13', 'city', 'crown',
    ['A Roman centurion, a captain of a hundred soldiers, came to Jesus: “Lord, my servant is lying at home, very sick.” Jesus said, “I will come.”', 'The centurion said, “I am not worthy for You to come to my house. Just speak the word, and my servant will be healed. I understand authority. I say go, and they go.”', 'Jesus was amazed: “I have not found such great faith in all Israel!” The servant was healed that very hour.'],
    'Speak the word only, and my servant shall be healed.', 'Matthew 8:8',
    'Great faith understands that God’s Word has authority.',
    'The centurion understood that authority works through words. Jesus called this great faith. Jesus has given you authority in His name (Mark 16:17–18). When you speak His Word, you are not hoping; you are exercising delegated authority.',
    'I have authority in the name of Jesus. I speak the Word and it is done.',
    'Lord, give me great faith like the centurion. Amen.', 'Speak a Bible promise over your home today.',
    [['What was the centurion?', 'A soldier captain', 'A fisherman', 'A priest', 0], ['What did he ask Jesus to do?', 'Speak the word only', 'Come quickly', 'Send a doctor', 0], ['What did Jesus say about his faith?', 'Great faith', 'Little faith', 'No faith', 0]],
    'CENTURION:Captain of a hundred|AUTHORITY:He understood it|SERVANT:He was healed|FAITH:Jesus called it great|WORD:Speak the ___ only'],
  ['jairus', 'Jairus’ Daughter', 'Mark 5:21–43', 'city', 'lamp',
    ['Jairus’ twelve-year-old daughter was dying. He fell at Jesus’ feet and begged, “Please come and lay Your hands on her so she will live!”', 'On the way, messengers came: “Your daughter is dead. Why trouble the Teacher?” Jesus said to Jairus, “Be not afraid, only believe.”', 'At the house Jesus took the girl’s hand and said, “Talitha cumi,” which means, “Little girl, arise!” She got up and walked, and Jesus told them to give her something to eat.'],
    'Be not afraid, only believe.', 'Mark 5:36',
    'When bad news comes, keep your eyes on Jesus and only believe.',
    'Jesus immediately spoke to Jairus’ heart when the bad report came. Fear and faith cannot both lead you. Jesus also put the mourners out: sometimes you need to keep unbelief away from you. Choose whose report you will believe.',
    'I am not afraid. I only believe. I believe the report of the Lord.',
    'Jesus, when I hear bad news, help me only believe. Amen.', 'Next time you hear bad news, say “I only believe.”',
    [['How old was the girl?', 'Twelve', 'Five', 'Twenty', 0], ['What did Jesus tell Jairus?', 'Only believe', 'Go home', 'It is too late', 0], ['What does Talitha cumi mean?', 'Little girl, arise', 'Good morning', 'Be quiet', 0]],
    'JAIRUS:The worried father|BELIEVE:Only ___|ARISE:Little girl, ___|TWELVE:Her age|HAND:Jesus took hers'],
  ['hem', 'The Touch of Faith', 'Mark 5:25–34', 'city', 'staff',
    ['A woman had been sick for twelve years. She had spent all her money on doctors, but she only got worse.', 'She heard about Jesus and kept saying, “If I may touch but His clothes, I shall be whole.” She pushed through the crowd and touched His robe. Instantly she was healed!', 'Jesus stopped: “Who touched Me? I felt power go out.” Trembling, she told Him everything. Jesus said, “Daughter, your faith has made you whole. Go in peace.”'],
    'Daughter, thy faith hath made thee whole.', 'Mark 5:34',
    'What you keep saying in faith shapes what you receive.',
    'She kept saying it (Mark 5:28): faith speaks before it receives. Many people touched Jesus in the crowd, but one touched Him with faith, and power flowed. Faith connects you to God’s power. Jesus also called her “daughter”: He restored her dignity, not just her body.',
    'My faith makes me whole. I receive God’s power by faith.',
    'Jesus, I reach out to You by faith today. Amen.', 'Write down one thing you are believing God for and say it every day this week.',
    [['How long was the woman sick?', 'Twelve years', 'Twelve days', 'One year', 0], ['What did she touch?', 'His clothes', 'His hand', 'His sandals', 0], ['What made her whole?', 'Her faith', 'Doctors', 'Money', 0]],
    'TOUCH:She reached out to ___|HEM:Edge of His robe|WHOLE:Made ___|POWER:Went out of Jesus|PEACE:Go in ___'],
  ['walk-water', 'Peter Walks on Water', 'Matthew 14:22–33', 'sea', 'boat',
    ['The disciples were in a boat, fighting strong winds in the night. Then they saw Jesus walking on the water towards them! They thought He was a ghost.', 'Jesus said, “Be of good cheer, it is I.” Peter said, “Lord, if it is You, tell me to come.” Jesus said, “Come.” Peter climbed out and walked on the water!', 'But when Peter looked at the wind and waves, he got scared and began to sink. “Lord, save me!” Jesus caught him at once.'],
    'Looking unto Jesus the author and finisher of our faith.', 'Hebrews 12:2',
    'Keep your eyes on Jesus, not on the storm.',
    'Peter walked on one word: “Come.” A single word from Jesus can hold you up. He sank when his focus shifted. Faith is sustained by focus. Even when you wobble, Jesus is right there and immediately reaches out. Get back up and keep walking.',
    'My eyes are on Jesus. His Word holds me up above every storm.',
    'Jesus, help me keep my eyes on You. Amen.', 'When you feel scared today, say, “I am looking at Jesus.”',
    [['What did the disciples think Jesus was?', 'A ghost', 'A fish', 'An angel', 0], ['What word did Jesus say to Peter?', 'Come', 'Stop', 'Wait', 0], ['Why did Peter sink?', 'He looked at the waves', 'He was heavy', 'He was tired', 0]],
    'PETER:He walked on water|WAVES:They frightened Peter|COME:Jesus said one word|SINK:What Peter began to do|FOCUS:Keep it on Jesus'],
  ['salt-light', 'Salt and Light', 'Matthew 5:13–16', 'mountain', 'lamp',
    ['Jesus sat on a mountain and taught the crowds. He said, “You are the salt of the earth.” Salt makes food tasty and keeps it from going bad.', 'Then He said, “You are the light of the world. A city on a hill cannot be hidden. Nobody lights a lamp and puts it under a basket!”', '“Let your light so shine before men, that they may see your good works, and glorify your Father in heaven.”'],
    'Ye are the light of the world.', 'Matthew 5:14',
    'You are not trying to become light. Jesus says you already are.',
    'Notice Jesus said “you are”, not “try to be”. Your identity comes first, then your actions. Because Christ lives in you, you carry His light. You make a difference by being who you are in Him: kind, truthful, joyful. That points people to the Father.',
    'I am the salt of the earth and the light of the world. I shine for Jesus.',
    'Jesus, help my light shine brightly today. Amen.', 'Do one good deed today that makes someone glorify God.',
    [['What does salt do?', 'Adds flavour and preserves', 'Makes things dark', 'Nothing', 0], ['Where should a lamp not go?', 'Under a basket', 'On a stand', 'In a room', 0], ['Who gets the glory?', 'Our Father in heaven', 'Ourselves', 'Our friends', 0]],
    'SALT:Of the earth|LIGHT:Of the world|LAMP:Put it on a stand|SHINE:Let your light ___|HILL:A city on one'],
  ['lords-prayer', 'Jesus Teaches Us to Pray', 'Matthew 6:5–13', 'mountain', 'sun',
    ['The disciples saw how Jesus prayed and asked, “Lord, teach us to pray.” Jesus said, “Do not pray to show off. Go into your room and talk to your Father in secret.”', '“Pray like this: Our Father which art in heaven, hallowed be Thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven.”', '“Give us this day our daily bread. Forgive us our debts as we forgive. Lead us not into temptation, but deliver us from evil.”'],
    'Our Father which art in heaven, Hallowed be thy name.', 'Matthew 6:9',
    'Prayer starts with “Father”. You are talking to Someone who loves you.',
    'Jesus taught us to call God “Father”. Later He said to ask the Father in His name (John 16:23–24). Prayer is fellowship with your Father, worship of His name, agreement with His will and receiving His supply. It is a relationship, not a ritual.',
    'I pray to my Father in Jesus’ name. He hears me and answers me.',
    'Our Father in heaven, Your will be done in my life today. Amen.', 'Pray the Lord’s Prayer slowly and think about each line.',
    [['How does the prayer start?', 'Our Father', 'Dear God', 'Hello', 0], ['Where should we pray in secret?', 'In our room', 'On the street', 'Nowhere', 0], ['Thy will be done in earth as it is in…', 'Heaven', 'Church', 'School', 0]],
    'FATHER:Our ___ in heaven|PRAYER:Talking to God|KINGDOM:Thy ___ come|BREAD:Daily ___|SECRET:Pray in ___'],
  ['two-builders', 'The Wise and Foolish Builders', 'Matthew 7:24–27', 'storm', 'wall',
    ['Jesus told a story. A wise man built his house on the rock. A foolish man built his house on the sand because it was quick and easy.', 'Then the rain came down, the floods came up and the winds blew hard against both houses.', 'The house on the rock stood firm! The house on the sand fell with a great crash. Jesus said, “Whoever hears My words and does them is like the wise man.”'],
    'Whosoever heareth these sayings of mine, and doeth them, I will liken him unto a wise man.', 'Matthew 7:24',
    'Hearing the Word is good. Doing the Word makes you strong.',
    'Both builders faced the same storm. Being a Christian does not mean no storms; it means you do not fall. James 1:22 says be doers of the Word, not hearers only. Every time you act on the Word, you are adding another stone to your foundation.',
    'I am a doer of the Word. My life is built on the Rock and I stand firm.',
    'Lord, help me not just hear Your Word but do it. Amen.', 'Do one thing from a Bible verse today.',
    [['Where did the wise man build?', 'On the rock', 'On the sand', 'On water', 0], ['What happened to the house on sand?', 'It fell', 'It stood', 'It floated', 0], ['The wise man hears and…', 'Does the Word', 'Forgets it', 'Argues', 0]],
    'ROCK:Wise foundation|SAND:Foolish foundation|STORM:It came to both|WISE:The builder on the rock|DOER:Be a ___ of the Word'],
  ['sower', 'The Sower and the Seed', 'Mark 4:1–20', 'field', 'tree',
    ['A farmer went out to sow seeds. Some fell on the path and birds ate them. Some fell on rocky ground, grew fast but dried up in the sun.', 'Some fell among thorns, which choked the little plants. But some fell on good soil and grew a big harvest: thirty, sixty, even a hundred times more!', 'Jesus explained: the seed is the Word of God, and the soil is our heart. A good heart hears the Word, accepts it and bears much fruit.'],
    'The sower soweth the word.', 'Mark 4:14',
    'Let God’s Word go deep into your heart.',
    'Jesus said this parable is the key to all the others (Mark 4:13). Everything in God’s kingdom works by seed: the Word planted in the heart grows by itself (Mark 4:26–28). Protect your heart from worry and distraction, which choke the Word.',
    'My heart is good ground. The Word grows in me and produces a hundredfold.',
    'Lord, make my heart good soil for Your Word. Amen.', 'Plant a seed in a cup and watch it grow, like the Word in you.',
    [['What is the seed?', 'The Word of God', 'Money', 'Rain', 0], ['What ate the seed on the path?', 'Birds', 'Cows', 'Ants', 0], ['How much did good soil produce?', 'Up to a hundred times', 'Nothing', 'Just one', 0]],
    'SOWER:He planted seeds|SEED:The Word of God|SOIL:Our heart is like it|THORNS:They choke the plants|HARVEST:Thirty, sixty, a hundred'],
  ['mustard-seed', 'The Mustard Seed', 'Matthew 13:31–32; 17:20', 'field', 'tree',
    ['Jesus held up a mustard seed, one of the smallest seeds of all. “The kingdom of heaven is like this seed.”', '“When it is planted, it grows bigger than all the garden plants and becomes a tree so big that birds come and make nests in its branches.”', 'Later He said, “If you have faith as a grain of mustard seed, you shall say to this mountain, Move, and it shall move. Nothing shall be impossible to you.”'],
    'If ye have faith as a grain of mustard seed… nothing shall be impossible unto you.', 'Matthew 17:20',
    'Small faith in a big God can move mountains.',
    'It is not the size of the seed but the life inside it that matters. Your faith is alive because it comes from God (Romans 12:3). Plant your faith by speaking to mountains, not just about them. Small beginnings in God become something great.',
    'I have the faith of God. Nothing is impossible to me.',
    'Lord, thank You that my faith in You can move mountains. Amen.', 'Find a tiny seed and keep it as a reminder that faith grows.',
    [['What is the mustard seed like?', 'Very small', 'Very big', 'Square', 0], ['What does it grow into?', 'A big tree', 'A flower', 'Grass', 0], ['What can faith move?', 'Mountains', 'Only small rocks', 'Nothing', 0]],
    'MUSTARD:A tiny seed|SEED:Small beginning|TREE:What it grows into|MOUNTAIN:Faith can move it|BIRDS:Nest in the branches'],
  ['prodigal', 'The Son Who Came Home', 'Luke 15:11–32', 'field', 'gift',
    ['A young man asked his father for his share of money, then left home and wasted it all on wild living. When a famine came, he ended up feeding pigs and was so hungry he wanted to eat their food.', 'He came to his senses: “I’ll go home and say, Father, I have sinned. Make me a servant.” While he was still far off, his father saw him and ran to him!', 'The father hugged him, gave him the best robe, a ring and new shoes, and threw a party. “My son was dead and is alive again; he was lost and is found!”'],
    'This my son was dead, and is alive again; he was lost, and is found.', 'Luke 15:24',
    'God runs to meet anyone who turns back to Him.',
    'The son wanted to come back as a servant, but the father restored him as a son: the robe (righteousness), the ring (authority) and the shoes (sonship, since servants went barefoot). God does not just forgive you; He restores your full position as His child.',
    'I am not a servant; I am a son of God. I wear the robe of righteousness.',
    'Father, thank You for always welcoming me home. Amen.', 'If you have done wrong, tell God and receive His forgiveness today.',
    [['What job did the son end up doing?', 'Feeding pigs', 'Fishing', 'Building', 0], ['What did the father do when he saw him?', 'Ran to him', 'Turned away', 'Shouted', 0], ['What did the father give him?', 'A robe, ring and shoes', 'A job', 'Some advice', 0]],
    'PRODIGAL:The son who left|FATHER:He ran to meet him|ROBE:The best one|RING:Sign of sonship|HOME:Where he returned'],
  ['ten-lepers', 'One Came Back', 'Luke 17:11–19', 'desert', 'staff',
    ['Ten men with leprosy stood far away and shouted, “Jesus, Master, have mercy on us!” Jesus said, “Go, show yourselves to the priests.”', 'As they went, they were healed! Their skin became clean. Nine kept walking.', 'But one, a Samaritan, came running back, shouting praise to God. He fell at Jesus’ feet and thanked Him. Jesus said, “Were there not ten healed? Arise, your faith has made you whole.”'],
    'In every thing give thanks.', '1 Thessalonians 5:18',
    'Thankful people go back to say thank you.',
    'Ten were cleansed, but the one who returned was made whole. Thanksgiving takes you deeper into what God has done. Gratitude keeps your heart soft and your faith strong. Make thanksgiving a lifestyle, not just an event.',
    'I am a thankful person. I give thanks in everything.',
    'Thank You, Jesus, for all You have done for me. Amen.', 'Write thank-you notes to God for ten things.',
    [['How many were healed?', 'Ten', 'One', 'Five', 0], ['How many came back?', 'One', 'Ten', 'Nine', 0], ['What did he do?', 'Thanked Jesus', 'Asked for more', 'Hid', 0]],
    'LEPERS:Ten were healed|THANKS:Only one gave it|CLEAN:Their skin became ___|TEN:How many were healed|GRATEFUL:Full of thanks'],
  ['bartimaeus', 'Blind Bartimaeus', 'Mark 10:46–52', 'city', 'staff',
    ['Blind Bartimaeus sat by the road in Jericho begging. He heard that Jesus was passing and shouted, “Jesus, Son of David, have mercy on me!”', 'People told him to be quiet, but he shouted even louder! Jesus stopped and called him. Bartimaeus threw off his cloak, jumped up and came.', 'Jesus asked, “What do you want Me to do for you?” “Lord, that I might receive my sight.” “Go, your faith has made you whole.” Immediately he could see, and he followed Jesus.'],
    'What wilt thou that I should do unto thee?', 'Mark 10:51',
    'Don’t let anyone silence your cry to Jesus.',
    'Jesus asked a blind man what he wanted, because faith is specific. Bartimaeus threw off his beggar’s cloak before he was healed: he acted like it was done. Faith refuses to be silenced and expects an answer.',
    'I am specific in my faith. I expect answers when I pray.',
    'Jesus, here is exactly what I need… I believe You hear me. Amen.', 'Write one specific prayer request and believe God for it.',
    [['Where did Bartimaeus sit?', 'By the road', 'In the temple', 'On a boat', 0], ['What did people tell him?', 'Be quiet', 'Shout louder', 'Go home', 0], ['What did he throw off?', 'His cloak', 'His shoes', 'His bag', 0]],
    'BLIND:Bartimaeus could not see|CLOAK:He threw it off|MERCY:Have ___ on me|SIGHT:What he received|JERICHO:Where he sat'],
  ['children-blessed', 'Let the Children Come', 'Mark 10:13–16', 'field', 'sun',
    ['Parents brought their children to Jesus so He could bless them. The disciples said, “Go away! Jesus is too busy.”', 'Jesus was not pleased. He said, “Let the little children come to Me. Do not stop them, for the kingdom of God belongs to such as these.”', 'Then He took the children in His arms, put His hands on them and blessed them.'],
    'Suffer the little children to come unto me, and forbid them not.', 'Mark 10:14',
    'Jesus always has time for you.',
    'Jesus said adults must receive the kingdom like a child: simply trusting. Children are not too young to know God, hear Him or be filled with the Holy Spirit (Acts 2:39: “the promise is unto you, and to your children”). You matter to Jesus right now.',
    'Jesus loves me and has time for me. The promise of the Spirit is for me too.',
    'Jesus, thank You that I can always come to You. Amen.', 'Spend five minutes just talking to Jesus as your friend.',
    [['Who tried to stop the children?', 'The disciples', 'The parents', 'Soldiers', 0], ['What did Jesus say?', 'Let the children come', 'Go away', 'Come later', 0], ['What did Jesus do?', 'Blessed them', 'Sent them home', 'Gave them money', 0]],
    'CHILDREN:Jesus welcomed them|BLESS:Jesus did it|ARMS:He took them in His ___|KINGDOM:Belongs to such as these|COME:Let the children ___'],
  ['mary-martha', 'Mary and Martha', 'Luke 10:38–42', 'city', 'lamp',
    ['Jesus visited His friends Martha and Mary. Martha rushed around the kitchen, busy with cooking and cleaning.', 'Mary sat at Jesus’ feet, listening to every word. Martha got upset: “Lord, tell Mary to help me!”', 'Jesus said kindly, “Martha, you are worried about many things, but only one thing is needed. Mary has chosen the good part.”'],
    'But one thing is needful: and Mary hath chosen that good part.', 'Luke 10:42',
    'Time with Jesus is the most important part of your day.',
    'Martha was serving Jesus; Mary was receiving from Him. Service is good, but it must flow from fellowship. Sitting in His presence and hearing His Word fills you up so you have something to give. Make room daily for “the good part”.',
    'I choose the good part. I sit at Jesus’ feet and hear His Word daily.',
    'Jesus, I want to spend time with You every day. Amen.', 'Set a time each day this week to read your Bible and pray.',
    [['What was Martha doing?', 'Working in the kitchen', 'Sleeping', 'Singing', 0], ['Where did Mary sit?', 'At Jesus’ feet', 'Outside', 'On the roof', 0], ['What did Mary choose?', 'The good part', 'The kitchen', 'Nothing', 0]],
    'MARY:Sat at Jesus’ feet|MARTHA:Busy in the kitchen|FEET:Mary sat at His ___|LISTEN:Mary did it|NEEDFUL:One thing is ___'],
  ['transfiguration', 'Glory on the Mountain', 'Matthew 17:1–8', 'mountain', 'sun',
    ['Jesus took Peter, James and John up a high mountain. Suddenly Jesus was transformed: His face shone like the sun and His clothes became white as light!', 'Moses and Elijah appeared and talked with Jesus. Peter said, “Let’s build three shelters!”', 'A bright cloud covered them and a voice said, “This is My beloved Son. Hear ye Him.” When they looked up, they saw no one but Jesus.'],
    'And we all, with open face beholding as in a glass the glory of the Lord, are changed into the same image.', '2 Corinthians 3:18',
    'Jesus is greater than every prophet. Listen to Him.',
    'The glory seen on the mountain was always inside Jesus. Paul says as you behold Jesus in the Word, you are changed from glory to glory. The more you look at Him, the more you become like Him. Christ in you is the hope of glory (Colossians 1:27).',
    'Christ in me is the hope of glory. I am changed from glory to glory.',
    'Jesus, as I look at You in Your Word, change me. Amen.', 'Read about Jesus in one of the Gospels today.',
    [['Who went up the mountain?', 'Peter, James and John', 'All twelve', 'Mary and Martha', 0], ['Who appeared with Jesus?', 'Moses and Elijah', 'David and Solomon', 'Abraham and Isaac', 0], ['What did the voice say?', 'Hear ye Him', 'Build shelters', 'Go home', 0]],
    'GLORY:Jesus shone with it|MOSES:Appeared on the mountain|ELIJAH:Also appeared|CLOUD:Bright and covering|SHONE:His face ___ like the sun'],
  ['ten-virgins', 'Ten Bridesmaids', 'Matthew 25:1–13', 'night', 'lamp',
    ['Ten bridesmaids waited with lamps for the bridegroom. Five were wise and brought extra oil. Five were foolish and did not.', 'The bridegroom was late, and they all fell asleep. At midnight a cry rang out: “The bridegroom is coming!” The foolish ones’ lamps were going out.', 'While they went to buy oil, the bridegroom arrived. The five wise bridesmaids went in to the wedding feast, and the door was shut.'],
    'Watch therefore, for ye know neither the day nor the hour.', 'Matthew 25:13',
    'Be ready for Jesus every day.',
    'Jesus is coming back. Oil is a picture of the Holy Spirit and a life full of His presence. You cannot borrow someone else’s relationship with God; you need your own. Staying full of the Spirit and the Word keeps your lamp burning.',
    'I am ready for Jesus. My lamp is full and my light is burning.',
    'Jesus, keep me ready and full of Your Spirit. Amen.', 'Do something today that keeps your spiritual lamp full: pray, read, worship.',
    [['How many bridesmaids were wise?', 'Five', 'Ten', 'Two', 0], ['What did the wise ones bring?', 'Extra oil', 'Extra food', 'Gifts', 0], ['When did the bridegroom come?', 'At midnight', 'At noon', 'In the morning', 0]],
    'LAMPS:They carried them|OIL:Extra was wise|READY:Be ___ for Jesus|MIDNIGHT:When the cry came|WATCH:___ therefore'],
  ['talents', 'Using Your Gifts', 'Matthew 25:14–30', 'city', 'gift',
    ['A master going on a journey gave his servants money called talents: five to one, two to another, and one to the last, each according to his ability.', 'The first two worked and doubled their money. The third was afraid, so he dug a hole and hid his talent in the ground.', 'When the master returned he said to the first two, “Well done, good and faithful servant!” But the one who hid his talent lost it.'],
    'Well done, thou good and faithful servant.', 'Matthew 25:21',
    'God gave you gifts to use, not to hide.',
    'Every believer has gifts from God (1 Peter 4:10). Fear made the third servant hide. God has not given you a spirit of fear but of power, love and a sound mind (2 Timothy 1:7). Faithfulness with what you have now leads to more.',
    'I use my gifts for God. I am faithful, and I will hear “well done”.',
    'Lord, show me my gifts and help me use them for You. Amen.', 'Use one of your talents to bless someone this week.',
    [['How many talents did the first servant get?', 'Five', 'Two', 'One', 0], ['What did the third servant do?', 'Hid it in the ground', 'Doubled it', 'Gave it away', 0], ['What did the master say to the faithful ones?', 'Well done', 'Too slow', 'Try again', 0]],
    'TALENTS:Money given to servants|FAITHFUL:Good and ___|HIDE:The fearful servant did it|GIFTS:God gives us these|SERVANT:Good and faithful ___'],
];

export const MORE3 = RAW.map(mk);
