import { mk, type Raw } from './mk';

// Old Testament, part 1. Verses are KJV.
const RAW: Raw[] = [
  ['enoch', 'Enoch Walks with God', 'Genesis 5:21–24; Hebrews 11:5', 'field', 'sun',
    ['Long ago lived a man called Enoch. Every day, Enoch talked with God, listened to God and loved God. They were best friends.', 'Enoch did not walk with God only on special days. He walked with Him for three hundred years, at home, at work and with his children.', 'One day Enoch and God walked so far together that God simply took him home to heaven. Enoch never died! The Bible says he pleased God.'],
    'By faith Enoch was translated that he should not see death.', 'Hebrews 11:5',
    'God does not only want to be your helper. He wants to be your friend, every single day.',
    'Walking with God means fellowship: talking with Him and hearing from Him through His Word. Jesus made this possible for you all the time, because the Holy Spirit lives in you. Fellowship is not a meeting once a week; it is a life lived with God.',
    'I walk with God every day. I am His friend and I please Him by faith.',
    'Father, I want to walk with You every day like Enoch did. Amen.', 'Talk to God three times today: morning, afternoon and night.',
    [['How long did Enoch walk with God?', 'Three days', 'Three hundred years', 'Thirty years', 1], ['What happened to Enoch at the end?', 'God took him to heaven', 'He sailed away', 'He became king', 0], ['What does the Bible say Enoch did?', 'He pleased God', 'He built a tower', 'He fought a giant', 0]],
    'ENOCH:He walked with God|WALK:Do it with God daily|FRIEND:What God wants to be to you|FAITH:Pleases God|HEAVEN:Where God took Enoch'],
  ['babel', 'The Tower of Babel', 'Genesis 11:1–9', 'city', 'wall',
    ['After the flood, people all spoke one language. They said, “Let us build a tower up to heaven and make a great name for ourselves.”', 'They baked bricks and built higher and higher. But they were building for their own glory, not for God.', 'God mixed up their languages so they could not understand each other. The building stopped, and people spread over the whole earth.'],
    'Except the LORD build the house, they labour in vain that build it.', 'Psalm 127:1',
    'Anything we build without God will not last. Anything we build with God will stand.',
    'At Babel, God scattered people by languages. At Pentecost, the Holy Spirit came and believers spoke in other tongues, and people from many nations heard the gospel in their own languages (Acts 2). What pride divided, the Holy Spirit unites.',
    'I build my life on God’s Word. My life brings glory to His name, not mine.',
    'Lord, help me to live for Your glory and not my own. Amen.', 'Build something today (blocks, a drawing, a kind act) and dedicate it to God.',
    [['What did the people want to build?', 'A boat', 'A tower to heaven', 'A temple', 1], ['Why did they want to build it?', 'To make a name for themselves', 'To worship God', 'To hide from rain', 0], ['What did God do?', 'Mixed up their languages', 'Sent a flood', 'Sent fire', 0]],
    'BABEL:The name of the tower|BRICKS:What they built with|TOWER:It reached high|PRIDE:Wanting glory for yourself|GLORY:Belongs to God'],
  ['isaac-altar', 'God Will Provide', 'Genesis 22:1–14', 'mountain', 'staff',
    ['God tested Abraham. “Take your son Isaac, the son you love, to a mountain and give him to Me.” Abraham’s heart was heavy, but he trusted God.', 'As they climbed, Isaac asked, “Father, where is the lamb?” Abraham said, “My son, God will provide Himself a lamb.”', 'At the top, God stopped Abraham. A ram was caught in a bush nearby! Abraham named the place “The Lord Will Provide.”'],
    'God will provide himself a lamb.', 'Genesis 22:8',
    'God never asks you for anything without having already provided what you need.',
    'Abraham’s words were a prophecy. Two thousand years later, on those same hills of Moriah, God gave His only Son, Jesus, the Lamb of God (John 1:29). Abraham did not have to give up his son, because God was going to give His.',
    'Jehovah Jireh is my God. He has already provided everything I need in Christ.',
    'Thank You, Father, for giving Jesus, the Lamb, for me. Amen.', 'Write “God will provide” on a card and put it where you will see it.',
    [['What did Isaac ask?', 'Where is the lamb?', 'Where is the water?', 'Where is mother?', 0], ['What did God provide?', 'A dove', 'A ram', 'A lion', 1], ['What does Jehovah Jireh mean?', 'The Lord will provide', 'The Lord is strong', 'The Lord is near', 0]],
    'ISAAC:Abraham’s son|LAMB:Jesus is the ___ of God|RAM:Caught in a bush|PROVIDE:God will ___|MORIAH:The mountain'],
  ['rebekah', 'Rebekah at the Well', 'Genesis 24', 'desert', 'jar',
    ['Abraham’s servant travelled far to find a wife for Isaac. At a well he prayed, “Lord, let the girl who offers water to my camels be the one.”', 'Before he had even finished praying, Rebekah came with her water jar. “Drink,” she said, “and I will draw water for your camels too!” Ten thirsty camels drink a lot!', 'The servant bowed and worshipped God. Rebekah went with him and became Isaac’s wife. God had answered his prayer exactly.'],
    'Before they call, I will answer.', 'Isaiah 65:24',
    'Kindness that goes the extra mile opens doors only God can open.',
    'God answered the servant before he finished praying. Prayer is not trying to convince an unwilling God; it is fellowship with a Father who already wants to bless. Rebekah’s generous heart placed her in the line that would bring the Messiah.',
    'God hears me when I pray. I am generous, and doors open for me.',
    'Lord, help me to be kind even when nobody asks. Amen.', 'Do a kind job today that nobody asked you to do.',
    [['What did the servant pray for?', 'Rain', 'A sign at the well', 'Gold', 1], ['What did Rebekah offer?', 'Water for the camels too', 'Bread', 'A place to sleep', 0], ['Who did Rebekah marry?', 'Jacob', 'Isaac', 'Joseph', 1]],
    'REBEKAH:Kind girl at the well|CAMELS:She gave them water|WELL:Where water is drawn|PRAYER:The servant’s request|KIND:Rebekah’s heart'],
  ['jacob-wrestles', 'Jacob Gets a New Name', 'Genesis 32', 'river', 'staff',
    ['Jacob had tricked his brother Esau years before. Now he was going home, and he was afraid. That night he was alone by the river Jabbok.', 'A Man came and wrestled with Jacob all night. Jacob held on and said, “I will not let You go unless You bless me!”', 'The Man said, “Your name is no longer Jacob, the trickster. It is Israel, because you have struggled with God and prevailed.” Jacob was changed forever.'],
    'Thy name shall be called no more Jacob, but Israel.', 'Genesis 32:28',
    'When you meet God, He gives you a new name and a new identity.',
    'Jacob means “supplanter”; Israel means “prince with God”. In Christ, God gave you a new identity too: child of God, saint, righteous. Do not let anyone, including you, call you by your old name. You are who God says you are.',
    'I have a new name. I am a child of God and a prince with God.',
    'Father, thank You for my new identity in Christ. Amen.', 'Find out what your name means, then write what God calls you: loved, chosen, righteous.',
    [['Who did Jacob wrestle?', 'Esau', 'A Man from God', 'A lion', 1], ['What did Jacob ask for?', 'A blessing', 'Money', 'A sword', 0], ['What was Jacob’s new name?', 'Abraham', 'Israel', 'Isaac', 1]],
    'ISRAEL:Jacob’s new name|WRESTLE:Jacob did it all night|BLESS:I will not let You go unless You ___ me|JABBOK:The river|NAME:God gave a new one'],
  ['joseph-prison', 'Joseph in Prison', 'Genesis 39–41', 'palace', 'crown',
    ['Joseph worked for Potiphar and did everything well. When he was tempted to do wrong, he said no and ran. But he was lied about and thrown in prison.', 'Even in prison, the Lord was with Joseph and gave him favour. He helped other prisoners and explained their dreams by God’s wisdom.', 'Two years later, Pharaoh had a dream nobody understood. Joseph was called from prison, explained it and became ruler over Egypt in one day!'],
    'But the LORD was with Joseph, and shewed him mercy, and gave him favour.', 'Genesis 39:21',
    'Doing right may cost you for a moment, but God’s favour always lifts you in the end.',
    'Favour is God’s grace on you that makes things work out. Joseph had favour in Potiphar’s house, in prison and in the palace. Your environment does not decide your favour; God’s presence does. Psalm 5:12 says He surrounds the righteous with favour as with a shield.',
    'The favour of God surrounds me like a shield. I am promoted by God.',
    'Lord, help me to do what is right even when it is hard. Amen.', 'When you are tempted today, do what Joseph did: say no and walk away.',
    [['What did Joseph do when tempted?', 'He ran away', 'He gave in', 'He cried', 0], ['Where was Joseph sent unfairly?', 'Prison', 'The desert', 'A ship', 0], ['Whose dream did Joseph explain at the end?', 'Pharaoh’s', 'His father’s', 'Potiphar’s', 0]],
    'FAVOUR:God gave it to Joseph|PRISON:Joseph was sent there|PHARAOH:King of Egypt|DREAM:Joseph explained it|RULER:What Joseph became'],
  ['burning-bush', 'The Burning Bush', 'Exodus 3–4', 'desert', 'lamp',
    ['Moses was looking after sheep in the desert when he saw a bush on fire, yet it was not burning up! He went closer to see.', 'God spoke from the bush: “Moses, take off your sandals, this is holy ground. I have seen My people suffer. I am sending you to Pharaoh.”', 'Moses said, “Who am I?” God answered, “I will be with you. Tell them I AM sent you.” Then God turned Moses’ staff into a snake and back to show His power.'],
    'And God said unto Moses, I AM THAT I AM.', 'Exodus 3:14',
    'It is not about who you are. It is about who is with you.',
    'Jesus later said, “Before Abraham was, I AM” (John 8:58). The God of the burning bush is Jesus. The bush burned without burning up: a picture of you, filled with God’s fire, the Holy Spirit, yet never consumed. You can carry His glory.',
    'The great I AM is with me. I am on fire for God and I am never burnt out.',
    'Lord, I am ready. Send me. Amen.', 'Tell God one thing you feel too small for, then say, “God is with me.”',
    [['What was strange about the bush?', 'It was blue', 'It burned but did not burn up', 'It could walk', 1], ['What name did God give?', 'I AM', 'The Great King', 'Mighty One', 0], ['What did Moses’ staff become?', 'A snake', 'A tree', 'A sword', 0]],
    'BUSH:It burned without burning up|MOSES:God called him|HOLY:Take off your sandals, it is ___ ground|IAM:God’s name (two words joined)|SANDALS:Moses took them off'],
  ['passover', 'The First Passover', 'Exodus 12', 'night', 'lamp',
    ['Pharaoh would not let God’s people go. God said, “Tonight I will pass through Egypt. Take a perfect lamb and put its blood on your door.”', 'Every family of Israel did it. They ate the meal dressed and ready to leave, with sandals on and staffs in their hands.', 'At midnight judgement came on Egypt, but wherever God saw the blood, He passed over. That night Pharaoh finally said, “Go!” and God’s people walked out free.'],
    'When I see the blood, I will pass over you.', 'Exodus 12:13',
    'The blood kept God’s people safe. The blood of Jesus keeps you safe.',
    '1 Corinthians 5:7 says Christ is our Passover, sacrificed for us. You are not protected because of how good your house is but because of the blood. Pleading the blood is not a magic word; it is declaring what Jesus’ sacrifice has done for you.',
    'I am covered by the blood of Jesus. No evil shall come near my dwelling.',
    'Thank You, Jesus, for Your blood that saves and protects me. Amen.', 'Ask your parents how your family can thank God for His protection tonight.',
    [['What was put on the doors?', 'Paint', 'The lamb’s blood', 'Flowers', 1], ['What did God do when He saw the blood?', 'Passed over', 'Knocked', 'Stopped', 0], ['Who is our Passover Lamb?', 'Moses', 'Jesus', 'Aaron', 1]],
    'BLOOD:On the doorposts|LAMB:It had to be perfect|PASSOVER:The feast name|EGYPT:Where they were slaves|FREE:What they became'],
  ['manna', 'Bread from Heaven', 'Exodus 16', 'desert', 'jar',
    ['In the desert there were no shops and no farms. The people grumbled, “We will starve!” But God said, “I will rain bread from heaven.”', 'Every morning the ground was covered with sweet flakes called manna. Each family collected just enough for that day. On the sixth day they collected double for the Sabbath.', 'For forty years God fed them every single day. They kept a jar of it to remember how faithful God was.'],
    'Man shall not live by bread alone, but by every word of God.', 'Luke 4:4',
    'God gives fresh supply every day, and He wants you to come to Him every day.',
    'Jesus said, “I am the bread of life” (John 6:35). Just as Israel needed fresh manna each morning, your spirit needs the Word each day. Yesterday’s Word is good, but today’s Word is fresh. Feeding on the Word is how your spirit grows strong.',
    'Jesus is my bread of life. I feed on the Word every day and my spirit is strong.',
    'Lord, give me my daily bread, and feed my heart with Your Word. Amen.', 'Read one Bible verse before breakfast today.',
    [['What was manna?', 'Bread from heaven', 'A river', 'A bird', 0], ['How often did they collect it?', 'Once a year', 'Every morning', 'Every month', 1], ['Who is the bread of life?', 'Moses', 'Jesus', 'Aaron', 1]],
    'MANNA:Bread from heaven|BREAD:Jesus is the ___ of life|DESERT:Where Israel walked|MORNING:When manna came|WORD:We live by every ___ of God'],
  ['ten-commandments', 'The Ten Commandments', 'Exodus 19–20', 'mountain', 'scroll',
    ['God’s people camped at Mount Sinai. Thunder rolled, lightning flashed and the mountain shook as God came down in fire and cloud.', 'Moses went up the mountain and God wrote Ten Commandments on stone tablets with His own finger: love God first, honour your parents, do not lie, steal or covet.', 'The laws showed how holy God is. They also showed people that they needed God’s help to live right.'],
    'If ye love me, keep my commandments.', 'John 14:15',
    'God’s ways are not to spoil your fun. They protect you and show you how to love.',
    'The Law was written on stone, outside people. In the New Covenant God writes His laws on your heart (Hebrews 8:10). Jesus fulfilled the Law, and the Holy Spirit now produces love in you, which is the fulfilling of the law (Romans 13:10).',
    'God’s law is written on my heart. I love God and I love people.',
    'Father, write Your Word on my heart so I love what You love. Amen.', 'Learn the first commandment by heart: love God with all your heart.',
    [['Where did God give the commandments?', 'Mount Sinai', 'Mount Carmel', 'Mount Zion', 0], ['What were they written on?', 'Paper', 'Stone tablets', 'Wood', 1], ['How many commandments?', 'Seven', 'Ten', 'Twelve', 1]],
    'SINAI:The mountain|TABLETS:Made of stone|TEN:How many commandments|HONOUR:Do this to your parents|LOVE:Fulfils the law'],
  ['bronze-serpent', 'Look and Live', 'Numbers 21:4–9', 'desert', 'staff',
    ['The people complained against God again, and poisonous snakes came into the camp. Many people were bitten.', 'They cried, “We have sinned! Pray for us!” God told Moses, “Make a bronze snake and lift it high on a pole.”', 'Anyone who was bitten and looked at the bronze snake lived! They did not have to do anything hard; they just had to look.'],
    'As Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up.', 'John 3:14',
    'Salvation is simple: look to Jesus and live.',
    'Jesus Himself explained this story. On the cross He was lifted up and took the poison of sin. Anyone who looks to Him in faith receives eternal life (John 3:15). Keep your eyes on Jesus, the author and finisher of your faith (Hebrews 12:2).',
    'I look to Jesus and I live. My eyes are fixed on Him.',
    'Jesus, I look to You. Thank You for taking the sting of sin. Amen.', 'Draw a cross and write under it: “Look and live.”',
    [['What bit the people?', 'Snakes', 'Lions', 'Bees', 0], ['What did Moses make?', 'A bronze snake on a pole', 'A golden calf', 'A tent', 0], ['What did people have to do to live?', 'Run fast', 'Look at it', 'Pay money', 1]],
    'SERPENT:Lifted up on a pole|BRONZE:Metal it was made of|POLE:Held the serpent up|LOOK:Do this and live|LIVE:What the people did'],
  ['spies', 'Joshua and Caleb', 'Numbers 13–14', 'mountain', 'tree',
    ['Moses sent twelve spies to look at the land God promised. They came back carrying a bunch of grapes so big two men had to carry it!', 'Ten spies said, “The people are giants. We are like grasshoppers!” But Joshua and Caleb said, “We are well able. The Lord is with us!”', 'The people believed the ten and were afraid. Only Joshua and Caleb, who believed God, later entered the Promised Land.'],
    'Let us go up at once, and possess it; for we are well able to overcome it.', 'Numbers 13:30',
    'What you believe about God decides what you see about your problems.',
    'The ten spies saw themselves as grasshoppers. How you see yourself matters. God says you are more than a conqueror, the righteousness of God, His workmanship. Faith sees what God sees. Caleb had “another spirit” (Numbers 14:24): a spirit of faith.',
    'I am well able. I have a spirit of faith, and I possess what God promised me.',
    'Lord, give me a heart like Caleb’s that believes You. Amen.', 'Say three things God says about you whenever you feel small today.',
    [['How many spies were sent?', 'Two', 'Twelve', 'Seven', 1], ['What did the ten spies say they were like?', 'Lions', 'Grasshoppers', 'Eagles', 1], ['Which two believed God?', 'Joshua and Caleb', 'Moses and Aaron', 'David and Saul', 0]],
    'CALEB:He said we are well able|JOSHUA:The other faithful spy|GIANTS:The ten were afraid of them|GRAPES:A huge bunch|ABLE:We are well ___'],
  ['rahab', 'Rahab and the Scarlet Cord', 'Joshua 2; 6:22–25', 'city', 'wall',
    ['Two spies went into Jericho. Rahab, a woman whose house was on the city wall, hid them under bundles of flax on her roof.', 'She said, “I know the Lord has given you this land. Your God is God in heaven and on earth. Please save my family!” They told her to tie a scarlet cord in her window.', 'When the walls fell, Rahab’s house was saved. She became part of God’s people, and later a great-great-grandmother of King David, in the family line of Jesus!'],
    'By faith the harlot Rahab perished not.', 'Hebrews 11:31',
    'It does not matter where you start. Faith in God changes your whole story.',
    'The scarlet cord is a picture of the blood of Jesus, just like the Passover blood. Rahab’s past did not stop God from honouring her faith. Grace means God gives what we do not deserve. In Christ your past does not define you; His blood does.',
    'My past does not define me. The blood of Jesus has made me new.',
    'Thank You, God, that Your grace is bigger than anyone’s past. Amen.', 'Be kind to someone others leave out.',
    [['Where did Rahab hide the spies?', 'On the roof', 'In a well', 'In the temple', 0], ['What colour was the cord?', 'Blue', 'Scarlet', 'Gold', 1], ['Whose family line did Rahab join?', 'Pharaoh’s', 'Jesus’', 'Goliath’s', 1]],
    'RAHAB:She hid the spies|SCARLET:The colour of the cord|CORD:Hung from the window|ROOF:Where the spies hid|GRACE:God’s undeserved favour'],
  ['sun-stands', 'The Day the Sun Stood Still', 'Joshua 10:1–14', 'mountain', 'sun',
    ['Five kings joined together to attack God’s friends in Gibeon. Joshua marched all night to help them.', 'In the middle of the battle, Joshua needed more daylight. He spoke boldly: “Sun, stand still! Moon, stay where you are!”', 'And the sun stood still for a whole day! The Bible says there was no day like it before or after, when the Lord listened to a man.'],
    'Sun, stand thou still upon Gibeon.', 'Joshua 10:12',
    'God gave people authority, and faith uses it with bold words.',
    'Joshua did not ask God to stop the sun. He spoke to the sun in faith, and God backed his words. Jesus gave believers authority in His name (Luke 10:19). The believer is not a beggar but a partner with God, speaking His will into the earth.',
    'I have authority in the name of Jesus. I speak, and God backs His Word.',
    'Lord, teach me to use the authority You gave me wisely. Amen.', 'Find Luke 10:19 and read it out loud three times.',
    [['What did Joshua speak to?', 'The sun and moon', 'A mountain', 'The sea', 0], ['How long did the sun stand still?', 'An hour', 'About a whole day', 'A week', 1], ['Who was Joshua helping?', 'Gibeon', 'Egypt', 'Babylon', 0]],
    'JOSHUA:He commanded the sun|SUN:It stood still|MOON:It stayed too|GIBEON:The city he helped|SPEAK:Faith does this'],
  ['hannah', 'Hannah’s Prayer', '1 Samuel 1–2', 'temple', 'lamp',
    ['Hannah longed for a baby, but year after year she had none. Someone teased her until she cried and could not eat.', 'At the temple Hannah poured out her heart to God. She prayed so deeply her lips moved but no sound came out. She promised to give her son back to God.', 'God answered! Hannah had a baby boy and called him Samuel, meaning “asked of God.” She sang a joyful song: “My heart rejoices in the Lord!”'],
    'For this child I prayed; and the LORD hath given me my petition.', '1 Samuel 1:27',
    'You can tell God everything, even your tears. He listens.',
    'When Eli blessed her, Hannah went home and was no longer sad, before she was even expecting a baby. That is faith: receiving the answer in your heart when you pray (Mark 11:24). Prayer with faith ends in praise.',
    'When I pray, I believe I receive. I end my prayers with praise.',
    'Father, thank You that I can pour out my heart to You. Amen.', 'Write a prayer for something you are hoping for, then thank God for hearing it.',
    [['What did Hannah long for?', 'A house', 'A baby', 'Gold', 1], ['Where did she pray?', 'At the temple', 'By the sea', 'On a boat', 0], ['What does Samuel mean?', 'Asked of God', 'Mighty one', 'Little lamb', 0]],
    'HANNAH:She prayed for a son|SAMUEL:Asked of God|TEMPLE:Where she prayed|ELI:The priest|SONG:Hannah sang one'],
  ['david-anointed', 'David Is Chosen', '1 Samuel 16:1–13', 'field', 'crown',
    ['God sent Samuel to Jesse’s house to anoint a new king. Jesse’s oldest son was tall and handsome. Surely it is him!', 'But God said, “People look at the outward appearance, but I look at the heart.” Seven sons passed by, and God chose none of them.', 'The youngest, David, was out with the sheep. When he came in, God said, “This is he.” Samuel poured oil on his head, and the Spirit of the Lord came upon David.'],
    'Man looketh on the outward appearance, but the LORD looketh on the heart.', '1 Samuel 16:7',
    'God sees what others miss. He is looking at your heart.',
    'David was anointed long before he wore a crown. In Christ, you have an anointing from the Holy One (1 John 2:20). You do not need to wait to be grown up to be used by God. The anointing in you is real now.',
    'I have an anointing from the Holy One. God sees my heart and calls me.',
    'Lord, give me a heart that pleases You. Amen.', 'Do something kind in secret today, just for God to see.',
    [['Whose house did Samuel visit?', 'Jesse’s', 'Saul’s', 'Eli’s', 0], ['What does God look at?', 'Height', 'The heart', 'Clothes', 1], ['What was David doing?', 'Keeping sheep', 'Fishing', 'Building', 0]],
    'DAVID:The youngest son|HEART:What God looks at|OIL:Poured on David’s head|SHEEP:David cared for them|JESSE:David’s father'],
  ['jonathan', 'David and Jonathan', '1 Samuel 18–20', 'field', 'sling',
    ['Prince Jonathan, King Saul’s son, loved David like a brother. He gave David his robe, his sword and his bow as a sign of friendship.', 'When Saul grew jealous and wanted to hurt David, Jonathan warned his friend, even though it was costly for him.', 'They agreed on a secret signal with arrows in a field. Then they said goodbye with tears and promised to be loyal forever.'],
    'A friend loveth at all times.', 'Proverbs 17:17',
    'A true friend helps you follow God’s plan, even when it costs them.',
    'Jonathan was heir to the throne, yet he gave David his robe: he honoured God’s choice above his own position. Jesus calls you His friend (John 15:15) and laid down His life for you. Godly friendships are covenant friendships.',
    'I am a friend of Jesus. I choose godly friends and I am a loyal friend.',
    'Jesus, thank You for being my best Friend. Help me be a good friend. Amen.', 'Do something special for a friend today.',
    [['Whose son was Jonathan?', 'Saul’s', 'Samuel’s', 'Jesse’s', 0], ['What did Jonathan give David?', 'His robe and sword', 'A horse', 'A crown', 0], ['What signal did they use?', 'Arrows', 'Fire', 'A trumpet', 0]],
    'JONATHAN:David’s best friend|ARROWS:The secret signal|ROBE:Jonathan gave it away|LOYAL:Faithful to a friend|FRIEND:Loves at all times'],
  ['david-spares', 'David Spares King Saul', '1 Samuel 24', 'mountain', 'staff',
    ['King Saul was hunting David with three thousand soldiers. David and his men hid deep in a dark cave.', 'Saul came into that very cave to rest. David’s men whispered, “This is your chance!” David crept close and cut off a corner of Saul’s robe, but he would not harm him.', 'Outside, David called, “My king! I could have hurt you, but I will not touch the Lord’s anointed.” Saul wept and said, “You are more righteous than I.”'],
    'Recompense to no man evil for evil.', 'Romans 12:17',
    'Getting even is easy. Leaving it to God takes real strength.',
    'David knew his throne would come from God, not from his own sword. When you know God’s promise, you do not have to fight dirty to get it. Walking in love, even towards people who are unkind, keeps you in the place of God’s protection.',
    'I walk in love. I do not repay evil for evil. God fights my battles.',
    'Lord, help me be kind to people who are unkind to me. Amen.', 'Pray for someone who has been unkind to you.',
    [['Where did David hide?', 'In a cave', 'In a tree', 'In a boat', 0], ['What did David cut?', 'A rope', 'Saul’s robe', 'His hair', 1], ['What did Saul say?', 'You are more righteous than I', 'I will catch you', 'Give me my robe', 0]],
    'CAVE:Where David hid|ROBE:David cut a corner off|SAUL:The jealous king|MERCY:Kindness not deserved|ANOINTED:Do not touch the Lord’s ___'],
  ['abigail', 'Wise Abigail', '1 Samuel 25', 'desert', 'gift',
    ['David’s men had protected Nabal’s sheep. But when David asked for food, Nabal rudely said no. David was angry and set out to punish him.', 'Nabal’s wife, Abigail, heard about it. Quickly she loaded donkeys with bread, raisins and cakes and rode out to meet David.', 'She bowed and spoke gently and wisely. David calmed down and said, “Blessed be God who sent you to stop me today!”'],
    'A soft answer turneth away wrath.', 'Proverbs 15:1',
    'Gentle, wise words can stop a fight before it starts.',
    'Abigail was a peacemaker. Jesus said peacemakers are called children of God (Matthew 5:9). The wisdom from above is “first pure, then peaceable, gentle” (James 3:17). The Holy Spirit can give you the right words in hard moments.',
    'I am a peacemaker. The wisdom of God speaks through me.',
    'Holy Spirit, give me gentle, wise words today. Amen.', 'If someone is angry today, answer softly.',
    [['Who was rude to David?', 'Nabal', 'Jonathan', 'Samuel', 0], ['What did Abigail bring?', 'Food', 'Swords', 'Gold', 0], ['How did Abigail speak?', 'Angrily', 'Gently and wisely', 'Loudly', 1]],
    'ABIGAIL:Wise peacemaker|NABAL:Rude husband|GENTLE:A soft answer|PEACE:Abigail made it|WISDOM:Comes from above'],
  ['mephibosheth', 'A Seat at the King’s Table', '2 Samuel 9', 'palace', 'crown',
    ['When David became king, he asked, “Is anyone left from Jonathan’s family? I want to show them God’s kindness.”', 'There was Mephibosheth, Jonathan’s son, who could not walk. He was afraid. In those days new kings often got rid of the old king’s family.', 'But David said, “Do not be afraid. You will eat at my table always, like one of my sons.” Mephibosheth received a place he could never earn.'],
    'He brought me to the banqueting house, and his banner over me was love.', 'Song of Solomon 2:4',
    'God’s grace gives you a place at His table, not because you earned it but because He loves you.',
    'This is a picture of the gospel. Because of a covenant (David’s promise to Jonathan), Mephibosheth was welcomed. Because of Jesus, you are seated with Christ in heavenly places (Ephesians 2:6). You are not a servant hoping for scraps; you are a son or daughter at the table.',
    'I am seated with Christ. I have a permanent place at my Father’s table.',
    'Thank You, Father, for welcoming me to Your table. Amen.', 'Invite someone who is often left out to sit with you.',
    [['Whose son was Mephibosheth?', 'Jonathan’s', 'Saul’s brother’s', 'Samuel’s', 0], ['Where did David let him eat?', 'At the king’s table', 'In the kitchen', 'Outside', 0], ['Why did David show kindness?', 'For Jonathan’s sake', 'For money', 'To look good', 0]],
    'KINDNESS:David showed it|TABLE:Mephibosheth ate there|KING:David|GRACE:Gift we cannot earn|COVENANT:A promise that binds'],
  ['temple-built', 'Solomon Builds the Temple', '1 Kings 6–8', 'temple', 'lamp',
    ['King Solomon built a beautiful temple for God, covered in gold, cedar wood and carvings of palm trees and flowers. It took seven years.', 'At the celebration, priests carried in the Ark of the Covenant, and singers and trumpeters praised God together as one voice.', 'Suddenly the glory of God filled the temple like a cloud, so strong that the priests could not stand! God had come to live among His people.'],
    'Know ye not that ye are the temple of God, and that the Spirit of God dwelleth in you?', '1 Corinthians 3:16',
    'God loves to live where He is welcome and praised.',
    'Solomon’s temple was glorious, but God has a greater temple now: you. Through Jesus, the glory that filled the temple lives in believers by the Holy Spirit. You are not just going to church; you are the church, a house for God’s presence.',
    'I am the temple of the living God. His glory dwells in me.',
    'Holy Spirit, fill me with Your glory. Amen.', 'Sing a praise song with your family today.',
    [['Who built the temple?', 'David', 'Solomon', 'Moses', 1], ['What filled the temple?', 'Water', 'God’s glory cloud', 'Smoke from a fire', 1], ['Who is God’s temple today?', 'Believers', 'A big building only', 'Nobody', 0]],
    'TEMPLE:God’s house|SOLOMON:He built it|GLORY:It filled the temple|CEDAR:Wood used|CLOUD:Glory came like one'],
  ['widow-zarephath', 'The Jar That Never Ran Out', '1 Kings 17:8–16', 'city', 'jar',
    ['There was a terrible drought. God sent Elijah to a widow in Zarephath. She had only a handful of flour and a little oil left.', 'Elijah said, “Make me a little cake first, then make some for you and your son. God says the flour and oil will not run out.”', 'She trusted God and did it. Day after day, the jar of flour and jug of oil never ran out until the rain came!'],
    'Give, and it shall be given unto you.', 'Luke 6:38',
    'When you put God first, He takes care of the rest.',
    'The widow’s miracle began when she gave from her little. Giving is a seed; God is the Lord of the harvest. This is not about getting things; it is about trusting God as your Source and living with an open hand.',
    'I put God first. I give, and it is given back to me, pressed down and running over.',
    'Father, help me trust You enough to give. Amen.', 'Share something you like with someone today.',
    [['What did the widow have little of?', 'Flour and oil', 'Water and fish', 'Gold and silver', 0], ['Who did she feed first?', 'Her son', 'Elijah', 'Herself', 1], ['What happened to the flour?', 'It ran out', 'It never ran out', 'It turned to gold', 1]],
    'WIDOW:She fed Elijah|FLOUR:It never ran out|OIL:Neither did this|GIVE:And it shall be given|ELIJAH:God’s prophet'],
  ['still-small-voice', 'The Still Small Voice', '1 Kings 19', 'mountain', 'dove',
    ['After a great victory, Elijah got scared and tired. He ran into the wilderness and said, “I’ve had enough.” He lay down and slept.', 'An angel touched him and gave him bread and water. Strengthened, he walked to Mount Horeb. There came a great wind, an earthquake and a fire, but God was not in them.', 'Then came a gentle whisper, a still small voice. It was God! He gave Elijah fresh direction and a friend called Elisha.'],
    'And after the fire a still small voice.', '1 Kings 19:12',
    'God often speaks quietly. Slow down and listen.',
    'The Holy Spirit leads believers mostly through an inward witness, a gentle knowing in your spirit (Romans 8:16). You hear it best when you are quiet and full of the Word. God also cares for your body: rest and food were part of Elijah’s healing.',
    'I am led by the Spirit of God. I hear His gentle voice in my heart.',
    'Holy Spirit, help me to be quiet and listen to You. Amen.', 'Sit quietly for two minutes today and just listen to God.',
    [['What did the angel give Elijah?', 'Bread and water', 'A sword', 'A cloak', 0], ['Was God in the earthquake?', 'Yes', 'No', 'Sometimes', 1], ['How did God speak?', 'A still small voice', 'Thunder', 'A trumpet', 0]],
    'WHISPER:God’s gentle voice|ELIJAH:He was tired|HOREB:The mountain|ANGEL:Brought food|LISTEN:Be still and ___'],
  ['chariots-fire', 'Elisha and the Chariots of Fire', '2 Kings 6:8–23', 'mountain', 'sun',
    ['An enemy king sent an army to capture Elisha. In the morning, Elisha’s servant saw horses and chariots all around the city. “What shall we do?” he cried.', 'Elisha said, “Do not fear. Those with us are more than those with them.” Then he prayed, “Lord, open his eyes.”', 'The servant looked again and saw the hills full of horses and chariots of fire all around Elisha! God’s army was there all along.'],
    'Fear not: for they that be with us are more than they that be with them.', '2 Kings 6:16',
    'God’s protection is around you, even when you cannot see it.',
    'Hebrews 1:14 says angels are ministering spirits sent to serve those who will inherit salvation. The spiritual world is real, and it is on your side. Elisha prayed for his servant’s eyes of understanding to open. Paul prayed the same for you (Ephesians 1:18).',
    'Those who are with me are more than those against me. Angels minister for me.',
    'Lord, open my eyes to see how big You are. Amen.', 'When you feel afraid today, say 2 Kings 6:16 out loud.',
    [['Who was the army after?', 'Elisha', 'David', 'Moses', 0], ['What did Elisha pray?', 'Open his eyes', 'Send rain', 'Make me strong', 0], ['What filled the hills?', 'Chariots of fire', 'Sheep', 'Trees', 0]],
    'ELISHA:The prophet|CHARIOTS:Made of fire|ANGELS:Ministering spirits|EYES:Elisha prayed for them to open|FEAR:Do not ___'],
  ['axe-head', 'The Floating Axe Head', '2 Kings 6:1–7', 'river', 'staff',
    ['The young prophets were cutting trees by the Jordan River to build a new meeting place. Elisha went with them.', 'Splash! One young man’s axe head flew off and sank into the river. “Oh no, master! It was borrowed!”', 'Elisha asked, “Where did it fall?” He cut a stick and threw it in. The heavy iron axe head floated to the top! God cares about small problems too.'],
    'Casting all your care upon him; for he careth for you.', '1 Peter 5:7',
    'No problem is too small for God to care about.',
    'Iron does not float, but the laws of nature bow to the God who made them. Faith brings the supernatural into everyday life. You do not need a huge crisis to see God move. He is interested in your homework, your friendships and the things you lose.',
    'God cares for me in big things and small things. I cast my cares on Him.',
    'Thank You, God, that You care about every part of my life. Amen.', 'Tell God about a small worry today and leave it with Him.',
    [['What fell in the river?', 'An axe head', 'A ring', 'A sandal', 0], ['Who did it belong to?', 'It was borrowed', 'Elisha', 'The king', 0], ['What did the iron do?', 'Sank deeper', 'Floated', 'Melted', 1]],
    'AXE:Its head fell in the river|IRON:Heavy metal that floated|JORDAN:The river|STICK:Elisha threw it|CARE:God does this for you'],
  ['widows-oil', 'The Widow’s Oil', '2 Kings 4:1–7', 'city', 'jar',
    ['A widow owed money, and the lender was coming to take her two sons as slaves. She cried to Elisha for help.', 'Elisha asked, “What do you have in the house?” “Only a little jar of oil.” He said, “Borrow empty jars from all your neighbours, not a few!”', 'She shut the door and poured. The oil kept flowing until every jar was full! She sold the oil, paid the debt and lived on the rest.'],
    'My God shall supply all your need according to his riches in glory by Christ Jesus.', 'Philippians 4:19',
    'God starts with what you already have.',
    'The oil stopped flowing only when the jars ran out. God’s supply was limited by her preparation, not His power. Faith makes room. Oil in the Bible often pictures the Holy Spirit: there is always more of Him for a heart that is open and ready.',
    'God supplies all my need. I make room for His overflow.',
    'Lord, I give You what I have. Fill it with Your blessing. Amen.', 'Make a list of five things God has already given you.',
    [['What did the widow have?', 'A little oil', 'A little bread', 'A sheep', 0], ['What did she borrow?', 'Money', 'Empty jars', 'A donkey', 1], ['When did the oil stop?', 'When jars ran out', 'After one jar', 'Never', 0]],
    'OIL:It kept flowing|JARS:She borrowed many|WIDOW:She cried to Elisha|SUPPLY:God shall ___ all your need|DEBT:Money owed'],
  ['shunammite', 'The Shunammite’s Son', '2 Kings 4:8–37', 'city', 'lamp',
    ['A kind woman in Shunem built a little room for Elisha with a bed, a table and a lamp. God blessed her with a son.', 'Years later, the boy became sick and died. The mother laid him on Elisha’s bed and rode to find the prophet. When asked, she said, “It is well.”', 'Elisha came, prayed and stretched himself over the boy. The child sneezed seven times and opened his eyes! She bowed and took her son.'],
    'It is well.', '2 Kings 4:26',
    'Faith keeps speaking “It is well” until it is well.',
    'The Shunammite refused to speak death over her son. She held to the promise God had given her. Your words should agree with God’s Word, even in difficult moments. Death has been defeated by Jesus, and life is the believer’s portion.',
    'It is well with me. I speak life, and I refuse to speak fear.',
    'Lord, help me to speak words of faith even when things look hard. Amen.', 'Whenever someone asks how you are today, answer with faith.',
    [['What did the woman build for Elisha?', 'A room', 'A boat', 'A well', 0], ['What did she say?', 'It is well', 'All is lost', 'Help me', 0], ['How many times did the boy sneeze?', 'Three', 'Seven', 'Twelve', 1]],
    'SHUNEM:Where she lived|ROOM:Built for Elisha|WELL:It is ___|SNEEZE:The boy did it seven times|LIFE:God’s gift'],
];

export const MORE1 = RAW.map(mk);
